#!/usr/bin/env bash
# setup-litestream.sh — Install Litestream, configure for S3, start replication, verify.
set -euo pipefail

###############################################################################
# Configuration (override via environment variables)
###############################################################################
LITESTREAM_VERSION="${LITESTREAM_VERSION:-latest}"
DB_PATH="${DB_PATH:-/data/app.db}"
S3_BUCKET="${S3_BUCKET:?S3_BUCKET is required}"
S3_PATH="${S3_PATH:-$(basename "$DB_PATH" .db)}"
S3_REGION="${S3_REGION:-us-east-1}"
SYNC_INTERVAL="${SYNC_INTERVAL:-1s}"
SNAPSHOT_INTERVAL="${SNAPSHOT_INTERVAL:-1h}"
RETENTION="${RETENTION:-168h}"
CONFIG_PATH="${CONFIG_PATH:-/etc/litestream.yml}"
METRICS_ADDR="${METRICS_ADDR:-:9090}"

# S3 credentials (must be set)
: "${LITESTREAM_ACCESS_KEY_ID:?LITESTREAM_ACCESS_KEY_ID is required}"
: "${LITESTREAM_SECRET_ACCESS_KEY:?LITESTREAM_SECRET_ACCESS_KEY is required}"

###############################################################################
# Helpers
###############################################################################
log() { echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) [setup] $*"; }
die() { log "ERROR: $*"; exit 1; }

check_root() {
  if [ "$(id -u)" -ne 0 ]; then
    die "This script must be run as root (or via sudo)"
  fi
}

###############################################################################
# 1. Install Litestream
###############################################################################
install_litestream() {
  if command -v litestream &>/dev/null; then
    log "Litestream already installed: $(litestream version)"
    return 0
  fi

  log "Installing Litestream..."
  ARCH=$(uname -m)
  case "$ARCH" in
    x86_64)  ARCH="amd64" ;;
    aarch64) ARCH="arm64" ;;
    armv7l)  ARCH="arm7"  ;;
    *)       die "Unsupported architecture: $ARCH" ;;
  esac

  OS=$(uname -s | tr '[:upper:]' '[:lower:]')
  if [ "$OS" != "linux" ]; then
    die "This script supports Linux only. For macOS, use: brew install benbjohnson/litestream/litestream"
  fi

  if [ "$LITESTREAM_VERSION" = "latest" ]; then
    DOWNLOAD_URL="https://github.com/benbjohnson/litestream/releases/latest/download/litestream-v0.3.13-linux-${ARCH}.tar.gz"
  else
    DOWNLOAD_URL="https://github.com/benbjohnson/litestream/releases/download/v${LITESTREAM_VERSION}/litestream-v${LITESTREAM_VERSION}-linux-${ARCH}.tar.gz"
  fi

  TMPDIR=$(mktemp -d)
  trap "rm -rf $TMPDIR" EXIT

  log "Downloading from $DOWNLOAD_URL"
  if command -v curl &>/dev/null; then
    curl -fsSL "$DOWNLOAD_URL" | tar xz -C "$TMPDIR"
  elif command -v wget &>/dev/null; then
    wget -qO- "$DOWNLOAD_URL" | tar xz -C "$TMPDIR"
  else
    die "curl or wget is required"
  fi

  mv "$TMPDIR/litestream" /usr/local/bin/litestream
  chmod +x /usr/local/bin/litestream

  log "Installed: $(litestream version)"
}

###############################################################################
# 2. Configure for S3
###############################################################################
configure_litestream() {
  log "Writing configuration to $CONFIG_PATH"

  mkdir -p "$(dirname "$CONFIG_PATH")"
  mkdir -p "$(dirname "$DB_PATH")"

  cat > "$CONFIG_PATH" <<EOF
# Litestream configuration — generated by setup-litestream.sh
# $(date -u +%Y-%m-%dT%H:%M:%SZ)

addr: "${METRICS_ADDR}"

logging:
  level: info
  type: text

dbs:
  - path: ${DB_PATH}
    replicas:
      - type: s3
        bucket: ${S3_BUCKET}
        path: ${S3_PATH}
        region: ${S3_REGION}
        sync-interval: ${SYNC_INTERVAL}
        snapshot-interval: ${SNAPSHOT_INTERVAL}
        retention: ${RETENTION}
        retention-check-interval: 1h
        validation-interval: 12h
EOF

  log "Configuration written"
}

###############################################################################
# 3. Ensure database exists and is in WAL mode
###############################################################################
prepare_database() {
  if [ ! -f "$DB_PATH" ]; then
    log "Database does not exist yet — will be created by the application"
    log "Attempting restore from replica (if available)..."
    if litestream restore -if-replica-exists -o "$DB_PATH" -config "$CONFIG_PATH" 2>/dev/null; then
      log "Restored database from replica"
    else
      log "No existing replica found — database will be created fresh"
      return 0
    fi
  fi

  if [ -f "$DB_PATH" ]; then
    JOURNAL_MODE=$(sqlite3 "$DB_PATH" "PRAGMA journal_mode;" 2>/dev/null || echo "unknown")
    if [ "$JOURNAL_MODE" != "wal" ]; then
      log "Setting WAL mode (current: $JOURNAL_MODE)"
      sqlite3 "$DB_PATH" "PRAGMA journal_mode=WAL;"
    fi
    log "Database ready: $DB_PATH (journal_mode=WAL)"
  fi
}

###############################################################################
# 4. Start replication
###############################################################################
start_replication() {
  log "Starting Litestream replication..."

  if pgrep -x litestream &>/dev/null; then
    log "Litestream is already running (PID: $(pgrep -x litestream))"
    return 0
  fi

  # Start in background
  nohup litestream replicate -config "$CONFIG_PATH" >> /var/log/litestream.log 2>&1 &
  LITESTREAM_PID=$!
  log "Litestream started with PID $LITESTREAM_PID"

  # Wait for it to initialize
  sleep 3

  if ! kill -0 "$LITESTREAM_PID" 2>/dev/null; then
    die "Litestream exited unexpectedly. Check /var/log/litestream.log"
  fi

  log "Litestream is running"
}

###############################################################################
# 5. Verify
###############################################################################
verify() {
  log "Verifying setup..."

  # Check process
  if ! pgrep -x litestream &>/dev/null; then
    die "Litestream process is not running"
  fi
  log "✓ Litestream process running"

  # Check config
  if [ ! -f "$CONFIG_PATH" ]; then
    die "Config file not found: $CONFIG_PATH"
  fi
  log "✓ Config file exists: $CONFIG_PATH"

  # Check metrics endpoint
  if command -v curl &>/dev/null; then
    METRICS_PORT=$(echo "$METRICS_ADDR" | sed 's/.*://')
    if curl -sf "http://localhost:${METRICS_PORT}/metrics" &>/dev/null; then
      log "✓ Metrics endpoint responding on $METRICS_ADDR"
    else
      log "⚠ Metrics endpoint not responding yet (may need more time)"
    fi
  fi

  # Check database
  if [ -f "$DB_PATH" ]; then
    JOURNAL=$(sqlite3 "$DB_PATH" "PRAGMA journal_mode;" 2>/dev/null)
    if [ "$JOURNAL" = "wal" ]; then
      log "✓ Database in WAL mode"
    else
      log "⚠ Database not in WAL mode: $JOURNAL"
    fi
  else
    log "⚠ Database file does not exist yet (waiting for application)"
  fi

  log "Setup complete!"
  log "  Database: $DB_PATH"
  log "  Replica:  s3://${S3_BUCKET}/${S3_PATH}"
  log "  Metrics:  http://localhost:${METRICS_PORT:-9090}/metrics"
  log "  Logs:     /var/log/litestream.log"
}

###############################################################################
# Main
###############################################################################
main() {
  log "=== Litestream Setup ==="
  install_litestream
  configure_litestream
  prepare_database
  start_replication
  verify
}

main "$@"
