#!/usr/bin/env bash
#
# setup-coturn.sh — Install and configure coturn TURN server with TLS
#
# Usage:
#   chmod +x setup-coturn.sh
#   sudo ./setup-coturn.sh --domain turn.example.com --secret MY_AUTH_SECRET
#
# Options:
#   --domain    FQDN of the TURN server (required)
#   --secret    Shared secret for HMAC-based auth (required)
#   --port      TURN listening port (default: 3478)
#   --tls-port  TLS listening port (default: 443)
#   --relay-min Minimum relay port (default: 49152)
#   --relay-max Maximum relay port (default: 65535)
#   --certbot   Use certbot to obtain TLS certs (default: false)
#
# Prerequisites:
#   - Ubuntu/Debian-based system
#   - Root or sudo access
#   - DNS A record pointing to this server (for TLS)
#
# This script:
#   1. Installs coturn
#   2. Generates or obtains TLS certificates
#   3. Writes a production-ready /etc/turnserver.conf
#   4. Enables and starts the coturn service
#

set -euo pipefail

# --- Defaults ---
TURN_DOMAIN=""
AUTH_SECRET=""
TURN_PORT=3478
TLS_PORT=443
RELAY_MIN=49152
RELAY_MAX=65535
USE_CERTBOT=false

# --- Parse Arguments ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)    TURN_DOMAIN="$2"; shift 2 ;;
    --secret)    AUTH_SECRET="$2"; shift 2 ;;
    --port)      TURN_PORT="$2"; shift 2 ;;
    --tls-port)  TLS_PORT="$2"; shift 2 ;;
    --relay-min) RELAY_MIN="$2"; shift 2 ;;
    --relay-max) RELAY_MAX="$2"; shift 2 ;;
    --certbot)   USE_CERTBOT=true; shift ;;
    *)           echo "Unknown option: $1"; exit 1 ;;
  esac
done

if [[ -z "$TURN_DOMAIN" || -z "$AUTH_SECRET" ]]; then
  echo "Error: --domain and --secret are required."
  echo "Usage: sudo $0 --domain turn.example.com --secret MY_SECRET"
  exit 1
fi

if [[ $EUID -ne 0 ]]; then
  echo "Error: This script must be run as root (use sudo)."
  exit 1
fi

echo "=== Installing coturn ==="
apt-get update -qq
apt-get install -y -qq coturn

# --- TLS Certificates ---
CERT_DIR="/etc/turnserver/certs"
mkdir -p "$CERT_DIR"

if [[ "$USE_CERTBOT" == true ]]; then
  echo "=== Obtaining TLS certificate with certbot ==="
  apt-get install -y -qq certbot
  certbot certonly --standalone --non-interactive --agree-tos \
    --register-unsafely-without-email \
    -d "$TURN_DOMAIN" \
    --cert-path "$CERT_DIR/turn_server_cert.pem" \
    --key-path "$CERT_DIR/turn_server_pkey.pem"

  CERT_FILE="/etc/letsencrypt/live/$TURN_DOMAIN/fullchain.pem"
  KEY_FILE="/etc/letsencrypt/live/$TURN_DOMAIN/privkey.pem"

  # Set up auto-renewal hook to restart coturn
  cat > /etc/letsencrypt/renewal-hooks/post/coturn.sh << 'HOOK'
#!/bin/bash
systemctl restart coturn
HOOK
  chmod +x /etc/letsencrypt/renewal-hooks/post/coturn.sh
else
  echo "=== Generating self-signed TLS certificate ==="
  CERT_FILE="$CERT_DIR/turn_server_cert.pem"
  KEY_FILE="$CERT_DIR/turn_server_pkey.pem"

  openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
    -keyout "$KEY_FILE" \
    -out "$CERT_FILE" \
    -subj "/CN=$TURN_DOMAIN" \
    -addext "subjectAltName=DNS:$TURN_DOMAIN"

  echo "Self-signed certificate generated at $CERT_FILE"
  echo "For production, use --certbot or provide your own certs."
fi

# Detect external IP
EXTERNAL_IP=$(curl -4 -s https://ifconfig.me || hostname -I | awk '{print $1}')
echo "Detected external IP: $EXTERNAL_IP"

# --- Write coturn configuration ---
echo "=== Writing /etc/turnserver.conf ==="
cat > /etc/turnserver.conf << CONF
# coturn TURN Server Configuration
# Generated by setup-coturn.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Network
listening-port=$TURN_PORT
tls-listening-port=$TLS_PORT
listening-ip=0.0.0.0
external-ip=$EXTERNAL_IP
relay-ip=0.0.0.0
min-port=$RELAY_MIN
max-port=$RELAY_MAX

# Domain
realm=$TURN_DOMAIN
server-name=$TURN_DOMAIN

# Authentication (HMAC-based ephemeral credentials)
use-auth-secret
static-auth-secret=$AUTH_SECRET

# TLS
cert=$CERT_FILE
pkey=$KEY_FILE
# Require TLS 1.2+
no-tlsv1
no-tlsv1_1
cipher-list="ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256"

# Security
no-multicast-peers
stale-nonce=600
fingerprint
lt-cred-mech

# Performance
total-quota=100
bps-capacity=0
max-bps=0

# Logging
log-file=/var/log/turnserver/turnserver.log
simple-log
new-log-timestamp

# Misc
proc-user=turnserver
proc-group=turnserver
no-stdout-log
CONF

# --- Create log directory ---
mkdir -p /var/log/turnserver
chown turnserver:turnserver /var/log/turnserver 2>/dev/null || true

# --- Enable coturn as a service ---
echo "=== Enabling coturn service ==="

# On Debian/Ubuntu, coturn is disabled by default
if [[ -f /etc/default/coturn ]]; then
  sed -i 's/^#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn
fi

systemctl enable coturn
systemctl restart coturn

echo ""
echo "=== coturn TURN server setup complete ==="
echo ""
echo "Configuration: /etc/turnserver.conf"
echo "Listening:     $TURN_DOMAIN:$TURN_PORT (UDP/TCP)"
echo "TLS:           $TURN_DOMAIN:$TLS_PORT (TLS)"
echo "Relay ports:   $RELAY_MIN-$RELAY_MAX"
echo ""
echo "Test connectivity:"
echo "  turnutils_stunclient $TURN_DOMAIN"
echo "  turnutils_uclient -u testuser -w testpass $TURN_DOMAIN"
echo ""
echo "Generate ephemeral credentials (Node.js):"
echo "  const crypto = require('crypto');"
echo "  const ttl = 86400;"
echo "  const ts = Math.floor(Date.now()/1000) + ttl;"
echo "  const username = ts + ':myuser';"
echo "  const hmac = crypto.createHmac('sha1', '$AUTH_SECRET');"
echo "  hmac.update(username);"
echo "  const credential = hmac.digest('base64');"
echo ""
echo "Firewall rules to open:"
echo "  ufw allow $TURN_PORT/tcp"
echo "  ufw allow $TURN_PORT/udp"
echo "  ufw allow $TLS_PORT/tcp"
echo "  ufw allow $RELAY_MIN:$RELAY_MAX/udp"
