#!/usr/bin/env bash
#
# setup-traefik.sh — Deploy Traefik with Docker Compose or Helm
#
# Usage:
#   ./setup-traefik.sh docker [--domain DOMAIN] [--email EMAIL] [--staging]
#   ./setup-traefik.sh helm   [--domain DOMAIN] [--email EMAIL] [--namespace NS] [--staging]
#   ./setup-traefik.sh --help
#
# Examples:
#   ./setup-traefik.sh docker --domain example.com --email admin@example.com
#   ./setup-traefik.sh helm --domain example.com --email admin@example.com --namespace traefik
#   ./setup-traefik.sh docker --staging   # Use Let's Encrypt staging for testing
#
# What it does:
#   Docker mode: Creates docker-compose.yaml, traefik.yaml, dynamic config, and acme.json.
#                Sets up Let's Encrypt, dashboard (BasicAuth), and Prometheus metrics.
#   Helm mode:   Installs Traefik via Helm chart with production-ready values.
#                Configures Let's Encrypt, metrics, and dashboard IngressRoute.
#

set -euo pipefail

# Defaults
DOMAIN="${DOMAIN:-example.com}"
EMAIL="${EMAIL:-admin@example.com}"
NAMESPACE="traefik"
STAGING=false
MODE=""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log()   { echo -e "${GREEN}[✓]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
err()   { echo -e "${RED}[✗]${NC} $*" >&2; }
info()  { echo -e "${BLUE}[i]${NC} $*"; }

usage() {
    sed -n '3,14p' "$0" | sed 's/^# \?//'
    exit 0
}

parse_args() {
    if [[ $# -lt 1 ]]; then
        usage
    fi

    MODE="$1"; shift

    if [[ "$MODE" == "--help" || "$MODE" == "-h" ]]; then
        usage
    fi

    while [[ $# -gt 0 ]]; do
        case "$1" in
            --domain)   DOMAIN="$2"; shift 2 ;;
            --email)    EMAIL="$2"; shift 2 ;;
            --namespace) NAMESPACE="$2"; shift 2 ;;
            --staging)  STAGING=true; shift ;;
            --help|-h)  usage ;;
            *) err "Unknown option: $1"; usage ;;
        esac
    done
}

generate_password() {
    openssl rand -base64 16 2>/dev/null || head -c 16 /dev/urandom | base64
}

# ─── Docker Compose Deployment ───────────────────────────────────────────────

setup_docker() {
    local dir="traefik-deployment"
    info "Setting up Traefik with Docker Compose in ./${dir}/"

    mkdir -p "${dir}/dynamic"
    cd "${dir}"

    # Generate dashboard password
    local password
    password=$(generate_password)
    local hashed
    if command -v htpasswd &>/dev/null; then
        hashed=$(echo "$password" | htpasswd -niB admin | head -1)
    else
        warn "htpasswd not found — using placeholder. Run: apt install apache2-utils"
        hashed='admin:$2y$05$placeholder'
    fi
    # Escape $ for docker-compose
    local escaped_hash="${hashed//\$/\$\$}"

    # ACME server
    local acme_server=""
    if [[ "$STAGING" == true ]]; then
        acme_server='caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"'
        warn "Using Let's Encrypt STAGING server (certs will not be trusted)"
    fi

    # ── traefik.yml (static config) ──
    cat > traefik.yml <<YAML
# Traefik Static Configuration
# Generated by setup-traefik.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
  metrics:
    address: ":8082"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${EMAIL}"
      storage: /data/acme.json
      ${acme_server}
      httpChallenge:
        entryPoint: web

log:
  level: INFO
  format: json

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-499"
      - "500-599"

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

ping:
  entryPoint: web
YAML
    log "Created traefik.yml"

    # ── Dynamic config ──
    cat > dynamic/middlewares.yml <<YAML
http:
  middlewares:
    secure-headers:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        browserXssFilter: true
        frameDeny: true
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=()"
    rate-limit:
      rateLimit:
        average: 100
        burst: 200
        period: 1s
        sourceCriterion:
          ipStrategy:
            depth: 1
    compress:
      compress:
        excludedContentTypes:
          - "text/event-stream"
YAML
    log "Created dynamic/middlewares.yml"

    # ── docker-compose.yml ──
    cat > docker-compose.yml <<YAML
# Traefik Docker Compose — Production Setup
# Generated by setup-traefik.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

services:
  traefik:
    image: traefik:v3.2
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - traefik-certs:/data
      - traefik-logs:/var/log/traefik
    labels:
      - "traefik.enable=true"
      # Dashboard
      - "traefik.http.routers.dashboard.rule=Host(\`traefik.${DOMAIN}\`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${escaped_hash}"
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Example service — remove or replace
  whoami:
    image: traefik/whoami:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(\`whoami.${DOMAIN}\`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
      - "traefik.http.routers.whoami.middlewares=secure-headers@file"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: bridge

volumes:
  traefik-certs:
  traefik-logs:
YAML
    log "Created docker-compose.yml"

    # Create acme.json with correct permissions
    touch acme.json
    chmod 600 acme.json
    log "Created acme.json (permissions 600)"

    echo ""
    log "Docker Compose setup complete in ./${dir}/"
    info "Dashboard credentials:"
    info "  Username: admin"
    info "  Password: ${password}"
    echo ""
    info "Next steps:"
    info "  1. Update domain '${DOMAIN}' to point to this server"
    info "  2. cd ${dir}"
    info "  3. docker compose up -d"
    info "  4. Visit https://traefik.${DOMAIN}"
    echo ""
    if [[ "$STAGING" == true ]]; then
        warn "Staging mode: Switch to production by removing caServer from traefik.yml"
    fi
}

# ─── Helm Deployment ─────────────────────────────────────────────────────────

setup_helm() {
    info "Setting up Traefik with Helm in namespace '${NAMESPACE}'"

    # Check prerequisites
    if ! command -v helm &>/dev/null; then
        err "helm not found. Install: https://helm.sh/docs/intro/install/"
        exit 1
    fi
    if ! command -v kubectl &>/dev/null; then
        err "kubectl not found."
        exit 1
    fi

    local dir="traefik-helm"
    mkdir -p "${dir}"
    cd "${dir}"

    local acme_server=""
    if [[ "$STAGING" == true ]]; then
        acme_server='caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"'
        warn "Using Let's Encrypt STAGING server"
    fi

    # ── values.yaml ──
    cat > values.yaml <<YAML
# Traefik Helm Values — Production
# Generated by setup-traefik.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

image:
  repository: traefik
  tag: "v3.2"

deployment:
  replicas: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

ports:
  web:
    port: 8000
    exposedPort: 80
    redirectTo:
      port: websecure
  websecure:
    port: 8443
    exposedPort: 443
    tls:
      enabled: true
  metrics:
    port: 8082
    exposedPort: 8082

service:
  type: LoadBalancer
  spec:
    externalTrafficPolicy: Local

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true

ingressClass:
  name: traefik
  isDefaultClass: true

ingressRoute:
  dashboard:
    enabled: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: "${EMAIL}"
      storage: /data/acme.json
      ${acme_server}
      httpChallenge:
        entryPoint: web

persistence:
  enabled: true
  size: 128Mi

logs:
  general:
    level: INFO
    format: json
  access:
    enabled: true
    format: json

metrics:
  prometheus:
    entryPoint: metrics
    addRoutersLabels: true
    addServicesLabels: true

securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532

podSecurityContext:
  fsGroup: 65532

priorityClassName: system-cluster-critical
YAML
    log "Created values.yaml"

    # ── Dashboard IngressRoute manifest ──
    cat > dashboard-ingressroute.yaml <<YAML
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: dashboard-auth
  namespace: ${NAMESPACE}
spec:
  basicAuth:
    secret: dashboard-auth-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: dashboard-auth-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  users: |
    admin:\$2y\$05\$CHANGE_ME_WITH_HTPASSWD_OUTPUT
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: ${NAMESPACE}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(\`traefik.${DOMAIN}\`)
      kind: Rule
      middlewares:
        - name: dashboard-auth
      services:
        - name: api@internal
          kind: TraefikService
  tls:
    certResolver: letsencrypt
YAML
    log "Created dashboard-ingressroute.yaml"

    echo ""
    info "Next steps:"
    info "  1. cd ${dir}"
    info "  2. helm repo add traefik https://traefik.github.io/charts && helm repo update"
    info "  3. helm install traefik traefik/traefik -n ${NAMESPACE} --create-namespace -f values.yaml"
    info "  4. Generate dashboard password: htpasswd -nbB admin <password>"
    info "  5. Update dashboard-auth-secret in dashboard-ingressroute.yaml"
    info "  6. kubectl apply -f dashboard-ingressroute.yaml"
    echo ""
}

# ─── Main ─────────────────────────────────────────────────────────────────────

parse_args "$@"

case "$MODE" in
    docker) setup_docker ;;
    helm)   setup_helm ;;
    *)      err "Unknown mode: $MODE (use 'docker' or 'helm')"; usage ;;
esac
