#!/usr/bin/env bash
set -euo pipefail

# Set up Traefik with Docker: creates network, volumes, directories, and initial configs.
# Usage: traefik-docker-setup.sh [--dir PATH] [--domain DOMAIN] [--email EMAIL] [--dashboard]

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m'

SETUP_DIR="./traefik"
DOMAIN="example.com"
ACME_EMAIL="admin@example.com"
ENABLE_DASHBOARD=false
NETWORK_NAME="proxy"

log_info() { echo -e "${GREEN}▸${NC} $1"; }
log_warn() { echo -e "${YELLOW}▸${NC} $1"; }
log_step() { echo -e "\n${GREEN}==>${NC} $1"; }

usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Set up a production-ready Traefik reverse proxy with Docker."
    echo ""
    echo "Options:"
    echo "  --dir PATH       Base directory for Traefik files (default: ./traefik)"
    echo "  --domain DOMAIN  Primary domain (default: example.com)"
    echo "  --email EMAIL    ACME email for Let's Encrypt (default: admin@example.com)"
    echo "  --dashboard      Enable dashboard with basic auth"
    echo "  -h, --help       Show this help message"
    echo ""
    echo "Example:"
    echo "  $0 --dir /opt/traefik --domain mysite.com --email me@mysite.com --dashboard"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --dir) SETUP_DIR="$2"; shift 2 ;;
        --domain) DOMAIN="$2"; shift 2 ;;
        --email) ACME_EMAIL="$2"; shift 2 ;;
        --dashboard) ENABLE_DASHBOARD=true; shift ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown option: $1"; usage; exit 1 ;;
    esac
done

# Check prerequisites
log_step "Checking prerequisites"
for cmd in docker; do
    if command -v "$cmd" &>/dev/null; then
        log_info "$cmd found: $(command -v "$cmd")"
    else
        echo -e "${RED}✗${NC} $cmd not found. Please install it first."
        exit 1
    fi
done

if docker compose version &>/dev/null; then
    COMPOSE_CMD="docker compose"
    log_info "Docker Compose (plugin) found"
elif command -v docker-compose &>/dev/null; then
    COMPOSE_CMD="docker-compose"
    log_info "docker-compose (standalone) found"
else
    echo -e "${RED}✗${NC} Docker Compose not found. Please install it."
    exit 1
fi

# Create directory structure
log_step "Creating directory structure at $SETUP_DIR"
mkdir -p "$SETUP_DIR"/{dynamic,certs,logs}
log_info "Created: $SETUP_DIR/{dynamic,certs,logs}"

# Create Docker network
log_step "Creating Docker network '$NETWORK_NAME'"
if docker network inspect "$NETWORK_NAME" &>/dev/null; then
    log_warn "Network '$NETWORK_NAME' already exists — skipping"
else
    docker network create "$NETWORK_NAME"
    log_info "Network '$NETWORK_NAME' created"
fi

# Generate static config
log_step "Generating static configuration"
cat > "$SETUP_DIR/traefik.yml" << STATIC_EOF
# Traefik v3 Static Configuration
# Generated by traefik-docker-setup.sh

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http3: {}

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: ${NETWORK_NAME}
  file:
    directory: /etc/traefik/dynamic
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${ACME_EMAIL}
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

api:
  dashboard: true
  insecure: false

log:
  level: INFO
  format: json

accessLog:
  format: json
  filters:
    statusCodes:
      - "400-499"
      - "500-599"

metrics:
  prometheus:
    entryPoint: metrics
    addRoutersLabels: true
    addServicesLabels: true
STATIC_EOF
log_info "Created $SETUP_DIR/traefik.yml"

# Generate dynamic config
log_step "Generating dynamic configuration"
cat > "$SETUP_DIR/dynamic/middlewares.yml" << 'DYNAMIC_EOF'
http:
  middlewares:
    security-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        referrerPolicy: "strict-origin-when-cross-origin"
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        customResponseHeaders:
          X-Powered-By: ""
          Server: ""

    rate-limit:
      rateLimit:
        average: 100
        burst: 200
        period: 1s

    compress:
      compress:
        excludedContentTypes:
          - "text/event-stream"

    standard-chain:
      chain:
        middlewares:
          - security-headers
          - rate-limit
          - compress
DYNAMIC_EOF
log_info "Created $SETUP_DIR/dynamic/middlewares.yml"

# Generate dashboard labels
DASHBOARD_LABELS=""
if [[ "$ENABLE_DASHBOARD" == "true" ]]; then
    DASHBOARD_LABELS=$(cat << DASH_EOF
      - "traefik.http.routers.dashboard.rule=Host(\`traefik.${DOMAIN}\`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=\${DASHBOARD_USER}"
DASH_EOF
    )
fi

# Generate docker-compose.yml
log_step "Generating docker-compose.yml"
cat > "$SETUP_DIR/docker-compose.yml" << COMPOSE_EOF
services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - letsencrypt:/letsencrypt
    networks:
      - ${NETWORK_NAME}
    labels:
      - "traefik.enable=true"
${DASHBOARD_LABELS}

volumes:
  letsencrypt:

networks:
  ${NETWORK_NAME}:
    external: true
COMPOSE_EOF
log_info "Created $SETUP_DIR/docker-compose.yml"

# Create .env template
log_step "Creating environment file"
cat > "$SETUP_DIR/.env" << ENV_EOF
# Traefik Environment Variables
# Generate DASHBOARD_USER with: echo \$(htpasswd -nB admin) | sed -e 's/\\$/\\$\\$/g'
DASHBOARD_USER=admin:\$\$apr1\$\$placeholder
# CF_DNS_API_TOKEN=your-cloudflare-token  # Uncomment for DNS challenge
ENV_EOF
log_info "Created $SETUP_DIR/.env"

# Create acme.json with correct permissions
log_step "Setting up certificate storage"
if docker volume inspect letsencrypt &>/dev/null; then
    log_warn "Volume 'letsencrypt' already exists — skipping"
else
    log_info "Volume 'letsencrypt' will be created on first run"
fi

# Summary
echo ""
echo "════════════════════════════════════════════════════"
echo -e "${GREEN}Traefik setup complete!${NC}"
echo "════════════════════════════════════════════════════"
echo ""
echo "Directory: $SETUP_DIR"
echo "Domain:    $DOMAIN"
echo "Email:     $ACME_EMAIL"
echo "Dashboard: $ENABLE_DASHBOARD"
echo ""
echo "Next steps:"
echo "  1. Review and edit $SETUP_DIR/traefik.yml"
echo "  2. Update $SETUP_DIR/.env with real credentials"
if [[ "$ENABLE_DASHBOARD" == "true" ]]; then
    echo "  3. Generate dashboard password:"
    echo "     htpasswd -nB admin | sed -e 's/\\\$/\\\$\\\$/g'"
    echo "  4. Set DNS record for traefik.$DOMAIN"
fi
echo ""
echo "Start Traefik:"
echo "  cd $SETUP_DIR && $COMPOSE_CMD up -d"
echo ""
