#!/usr/bin/env bash
# ==============================================================================
# generate-aggregate.sh — Scaffold aggregate root + commands + events + handler
#
# Usage:
#   ./generate-aggregate.sh Order                  # Generate Order aggregate (TypeScript)
#   ./generate-aggregate.sh Order --lang ts         # TypeScript (default)
#   ./generate-aggregate.sh Order --lang py         # Python
#   ./generate-aggregate.sh Order --outdir src/domain
#   ./generate-aggregate.sh Order --events "Created,Confirmed,Cancelled,Shipped"
#
# Generates:
#   <outdir>/<name>/
#   ├── events.ts       — Domain event interfaces
#   ├── commands.ts      — Command types
#   ├── aggregate.ts     — Aggregate root with rehydrate/apply
#   ├── handler.ts       — Command handler
#   └── aggregate.test.ts — Given-When-Then test template
#
# ==============================================================================
set -euo pipefail

# --- Defaults ---
NAME=""
LANG="ts"
OUTDIR="./src/domain"
EVENTS=""

# --- Parse arguments ---
if [ $# -eq 0 ]; then
  head -16 "$0" | tail -14
  exit 1
fi

NAME="$1"
shift

while [[ $# -gt 0 ]]; do
  case "$1" in
    --lang)    LANG="$2"; shift 2 ;;
    --outdir)  OUTDIR="$2"; shift 2 ;;
    --events)  EVENTS="$2"; shift 2 ;;
    -h|--help) head -16 "$0" | tail -14; exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

# --- Derived names ---
NAME_LOWER=$(echo "$NAME" | tr '[:upper:]' '[:lower:]')
NAME_UPPER=$(echo "$NAME" | tr '[:lower:]' '[:upper:]')
NAME_PASCAL="$NAME"

# Default events if not specified
if [ -z "$EVENTS" ]; then
  EVENTS="Created,Confirmed,Cancelled"
fi

IFS=',' read -ra EVENT_LIST <<< "$EVENTS"

DIR="${OUTDIR}/${NAME_LOWER}"
mkdir -p "$DIR"

log() { echo "[generate] $*"; }

# ==============================================================================
# TypeScript Generation
# ==============================================================================
generate_ts() {
  # --- events.ts ---
  cat > "${DIR}/events.ts" << TSEOF
// Domain events for ${NAME_PASCAL} aggregate
// Generated by generate-aggregate.sh

export interface DomainEvent {
  readonly type: string;
  readonly data: Record<string, unknown>;
  readonly metadata: {
    timestamp: string;
    version: number;
    causationId?: string;
    correlationId?: string;
  };
}

TSEOF

  for evt in "${EVENT_LIST[@]}"; do
    evt=$(echo "$evt" | xargs)  # trim whitespace
    cat >> "${DIR}/events.ts" << TSEOF
export interface ${NAME_PASCAL}${evt} extends DomainEvent {
  readonly type: '${NAME_PASCAL}${evt}';
  readonly data: {
    ${NAME_LOWER}Id: string;
    // TODO: Add fields specific to ${NAME_PASCAL}${evt}
  };
}

TSEOF
  done

  # Union type
  local union
  union=$(printf " | ${NAME_PASCAL}%s" "${EVENT_LIST[@]}")
  union="${union:3}" # remove leading " | "
  echo "export type ${NAME_PASCAL}Event = ${union};" >> "${DIR}/events.ts"

  # --- commands.ts ---
  cat > "${DIR}/commands.ts" << TSEOF
// Commands for ${NAME_PASCAL} aggregate
// Generated by generate-aggregate.sh

TSEOF

  for evt in "${EVENT_LIST[@]}"; do
    evt=$(echo "$evt" | xargs)
    local cmd_name
    # Convert past tense event to imperative command (simple heuristic)
    cmd_name="${evt%d}"  # Remove trailing 'd' (Created -> Create)
    cmd_name="${cmd_name%e}"  # Remove trailing 'e' if present (Cancelled -> Cancel)
    cat >> "${DIR}/commands.ts" << TSEOF
export interface ${cmd_name}${NAME_PASCAL} {
  readonly type: '${cmd_name}${NAME_PASCAL}';
  readonly ${NAME_LOWER}Id: string;
  readonly commandId: string;
  // TODO: Add fields specific to ${cmd_name}${NAME_PASCAL}
}

TSEOF
  done

  # --- aggregate.ts ---
  cat > "${DIR}/aggregate.ts" << TSEOF
// ${NAME_PASCAL} aggregate root with event sourcing
// Generated by generate-aggregate.sh

import { DomainEvent, ${NAME_PASCAL}Event } from './events';

type ${NAME_PASCAL}Status = $(printf "'%s' | " "${EVENT_LIST[@]}" | sed "s/ | $//; s/'Created'/'draft'/; s/'Confirmed'/'confirmed'/; s/'Cancelled'/'cancelled'/; s/'Shipped'/'shipped'/") ;

export class ${NAME_PASCAL}Aggregate {
  private id: string = '';
  private status: ${NAME_PASCAL}Status = 'draft';
  private version: number = 0;
  private uncommitted: DomainEvent[] = [];

  static rehydrate(events: DomainEvent[]): ${NAME_PASCAL}Aggregate {
    const agg = new ${NAME_PASCAL}Aggregate();
    events.forEach(e => agg.applyEvent(e, false));
    return agg;
  }

TSEOF

  # Generate command methods
  for evt in "${EVENT_LIST[@]}"; do
    evt=$(echo "$evt" | xargs)
    local method_name
    method_name=$(echo "${evt%d}" | sed 's/\(.\)/\L\1/')  # lowercase first letter, remove trailing d
    method_name="${method_name%e}"  # Remove trailing 'e'

    cat >> "${DIR}/aggregate.ts" << TSEOF
  ${method_name}(params: { ${NAME_LOWER}Id: string }): void {
    // TODO: Add invariant checks
    // if (this.status !== 'draft') throw new Error('Invalid state transition');
    this.applyEvent({
      type: '${NAME_PASCAL}${evt}',
      data: { ${NAME_LOWER}Id: params.${NAME_LOWER}Id },
      metadata: { timestamp: new Date().toISOString(), version: 1 },
    });
  }

TSEOF
  done

  cat >> "${DIR}/aggregate.ts" << TSEOF
  private applyEvent(event: DomainEvent, isNew: boolean = true): void {
    switch (event.type) {
TSEOF

  for evt in "${EVENT_LIST[@]}"; do
    evt=$(echo "$evt" | xargs)
    local status
    status=$(echo "$evt" | tr '[:upper:]' '[:lower:]')
    if [ "$evt" = "Created" ]; then status="draft"; fi
    cat >> "${DIR}/aggregate.ts" << TSEOF
      case '${NAME_PASCAL}${evt}':
        this.status = '${status}';
        break;
TSEOF
  done

  cat >> "${DIR}/aggregate.ts" << TSEOF
    }
    this.version++;
    if (isNew) this.uncommitted.push(event);
  }

  getId(): string { return this.id; }
  getStatus(): ${NAME_PASCAL}Status { return this.status; }
  getVersion(): number { return this.version; }
  getUncommitted(): DomainEvent[] { return [...this.uncommitted]; }
  clearUncommitted(): void { this.uncommitted = []; }
}
TSEOF

  # --- handler.ts ---
  cat > "${DIR}/handler.ts" << TSEOF
// Command handler for ${NAME_PASCAL} aggregate
// Generated by generate-aggregate.sh

import { ${NAME_PASCAL}Aggregate } from './aggregate';

interface EventStore {
  load(streamId: string): Promise<import('./events').DomainEvent[]>;
  append(streamId: string, events: import('./events').DomainEvent[], expectedVersion: number): Promise<void>;
  isDuplicate(commandId: string): Promise<boolean>;
}

export class ${NAME_PASCAL}CommandHandler {
  constructor(private readonly eventStore: EventStore) {}

TSEOF

  for evt in "${EVENT_LIST[@]}"; do
    evt=$(echo "$evt" | xargs)
    local method_name
    method_name=$(echo "${evt%d}" | sed 's/\(.\)/\L\1/')
    method_name="${method_name%e}"
    cat >> "${DIR}/handler.ts" << TSEOF
  async handle${evt%d}(cmd: { ${NAME_LOWER}Id: string; commandId: string }): Promise<void> {
    if (await this.eventStore.isDuplicate(cmd.commandId)) return;
    const history = await this.eventStore.load(cmd.${NAME_LOWER}Id);
    const aggregate = ${NAME_PASCAL}Aggregate.rehydrate(history);
    aggregate.${method_name}({ ${NAME_LOWER}Id: cmd.${NAME_LOWER}Id });
    await this.eventStore.append(cmd.${NAME_LOWER}Id, aggregate.getUncommitted(), history.length);
  }

TSEOF
  done

  echo "}" >> "${DIR}/handler.ts"

  # --- aggregate.test.ts ---
  cat > "${DIR}/aggregate.test.ts" << TSEOF
// Tests for ${NAME_PASCAL} aggregate (Given-When-Then)
// Generated by generate-aggregate.sh

import { ${NAME_PASCAL}Aggregate } from './aggregate';

describe('${NAME_PASCAL}Aggregate', () => {
  it('should create a new ${NAME_LOWER}', () => {
    // Given: no prior events
    const aggregate = ${NAME_PASCAL}Aggregate.rehydrate([]);

    // When: create
    aggregate.create({ ${NAME_LOWER}Id: 'test-1' });

    // Then: ${NAME_PASCAL}Created event emitted
    const events = aggregate.getUncommitted();
    expect(events).toHaveLength(1);
    expect(events[0].type).toBe('${NAME_PASCAL}Created');
  });

  // TODO: Add tests for other commands
  // it('should confirm a draft ${NAME_LOWER}', () => { ... });
  // it('should reject invalid state transitions', () => { ... });
});
TSEOF
}

# ==============================================================================
# Python Generation
# ==============================================================================
generate_py() {
  # --- events.py ---
  cat > "${DIR}/events.py" << PYEOF
"""Domain events for ${NAME_PASCAL} aggregate. Generated by generate-aggregate.sh."""
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

@dataclass(frozen=True)
class DomainEvent:
    event_type: str
    stream_id: str
    data: dict[str, Any]
    version: int
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    causation_id: str | None = None
    correlation_id: str | None = None

PYEOF

  for evt in "${EVENT_LIST[@]}"; do
    evt=$(echo "$evt" | xargs)
    cat >> "${DIR}/events.py" << PYEOF
@dataclass(frozen=True)
class ${NAME_PASCAL}${evt}(DomainEvent):
    """Raised when ${NAME_LOWER} is ${evt,,}."""
    event_type: str = "${NAME_PASCAL}${evt}"
    # TODO: Add typed fields

PYEOF
  done

  # --- commands.py ---
  cat > "${DIR}/commands.py" << PYEOF
"""Commands for ${NAME_PASCAL} aggregate. Generated by generate-aggregate.sh."""
from dataclasses import dataclass

PYEOF

  for evt in "${EVENT_LIST[@]}"; do
    evt=$(echo "$evt" | xargs)
    local cmd_name="${evt%d}"
    cmd_name="${cmd_name%e}"
    cat >> "${DIR}/commands.py" << PYEOF
@dataclass(frozen=True)
class ${cmd_name}${NAME_PASCAL}:
    ${NAME_LOWER}_id: str
    command_id: str
    # TODO: Add command-specific fields

PYEOF
  done

  # --- aggregate.py ---
  cat > "${DIR}/aggregate.py" << PYEOF
"""${NAME_PASCAL} aggregate root with event sourcing. Generated by generate-aggregate.sh."""
from .events import DomainEvent

class ${NAME_PASCAL}Aggregate:
    def __init__(self):
        self._id: str = ""
        self._status: str = "draft"
        self._version: int = 0
        self._uncommitted: list[DomainEvent] = []

    @classmethod
    def rehydrate(cls, events: list[DomainEvent]) -> "${NAME_PASCAL}Aggregate":
        agg = cls()
        for event in events:
            agg._apply(event, is_new=False)
        return agg

PYEOF

  for evt in "${EVENT_LIST[@]}"; do
    evt=$(echo "$evt" | xargs)
    local method_name
    method_name=$(echo "${evt%d}" | tr '[:upper:]' '[:lower:]')
    method_name="${method_name%e}"
    cat >> "${DIR}/aggregate.py" << PYEOF
    def ${method_name}(self, ${NAME_LOWER}_id: str) -> None:
        # TODO: Add invariant checks
        self._apply(DomainEvent(
            event_type="${NAME_PASCAL}${evt}",
            stream_id=${NAME_LOWER}_id,
            data={"${NAME_LOWER}_id": ${NAME_LOWER}_id},
            version=self._version + 1,
        ))

PYEOF
  done

  cat >> "${DIR}/aggregate.py" << PYEOF
    def _apply(self, event: DomainEvent, is_new: bool = True) -> None:
        match event.event_type:
PYEOF

  for evt in "${EVENT_LIST[@]}"; do
    evt=$(echo "$evt" | xargs)
    local status
    status=$(echo "$evt" | tr '[:upper:]' '[:lower:]')
    if [ "$evt" = "Created" ]; then status="draft"; fi
    cat >> "${DIR}/aggregate.py" << PYEOF
            case "${NAME_PASCAL}${evt}":
                self._status = "${status}"
PYEOF
  done

  cat >> "${DIR}/aggregate.py" << PYEOF
        self._version += 1
        if is_new:
            self._uncommitted.append(event)

    @property
    def uncommitted(self) -> list[DomainEvent]:
        return list(self._uncommitted)

    def clear_uncommitted(self) -> None:
        self._uncommitted.clear()
PYEOF

  # --- handler.py ---
  cat > "${DIR}/handler.py" << PYEOF
"""Command handler for ${NAME_PASCAL} aggregate. Generated by generate-aggregate.sh."""
from .aggregate import ${NAME_PASCAL}Aggregate

class ${NAME_PASCAL}CommandHandler:
    def __init__(self, event_store):
        self.event_store = event_store

PYEOF

  for evt in "${EVENT_LIST[@]}"; do
    evt=$(echo "$evt" | xargs)
    local method_name
    method_name=$(echo "${evt%d}" | tr '[:upper:]' '[:lower:]')
    method_name="${method_name%e}"
    cat >> "${DIR}/handler.py" << PYEOF
    async def handle_${method_name}(self, ${NAME_LOWER}_id: str, command_id: str) -> None:
        if await self.event_store.is_duplicate(command_id):
            return
        history = await self.event_store.load(${NAME_LOWER}_id)
        aggregate = ${NAME_PASCAL}Aggregate.rehydrate(history)
        aggregate.${method_name}(${NAME_LOWER}_id)
        await self.event_store.append(${NAME_LOWER}_id, aggregate.uncommitted, len(history))

PYEOF
  done

  # --- test file ---
  cat > "${DIR}/test_aggregate.py" << PYEOF
"""Tests for ${NAME_PASCAL} aggregate (Given-When-Then). Generated by generate-aggregate.sh."""
from .aggregate import ${NAME_PASCAL}Aggregate

def test_create_${NAME_LOWER}():
    # Given: no prior events
    aggregate = ${NAME_PASCAL}Aggregate.rehydrate([])
    # When: create
    aggregate.create("test-1")
    # Then
    events = aggregate.uncommitted
    assert len(events) == 1
    assert events[0].event_type == "${NAME_PASCAL}Created"

# TODO: Add more tests
PYEOF
}

# ==============================================================================
# Main
# ==============================================================================
case "$LANG" in
  ts|typescript) generate_ts ;;
  py|python)     generate_py ;;
  *) echo "Unsupported language: $LANG (use ts or py)" >&2; exit 1 ;;
esac

log "Generated ${NAME_PASCAL} aggregate in ${DIR}/"
log "Files:"
ls -1 "${DIR}/" | sed 's/^/  /'
log "Next steps:"
log "  1. Add domain-specific fields to events and commands"
log "  2. Implement invariant checks in aggregate methods"
log "  3. Wire up the command handler to your event store"
log "  4. Expand the test file with edge cases"
