#!/usr/bin/env bash
#
# ci-integration-setup.sh — Generate CI config snippets that invoke Dagger
#
# Usage:
#   ./ci-integration-setup.sh [--ci=github|gitlab|circleci|all] [--out=DIR] [--dagger-version=VERSION]
#
# Options:
#   --ci=PLATFORM         CI platform: github, gitlab, circleci, or all (default: all)
#   --out=DIR             Output directory (default: current directory)
#   --dagger-version=VER  Dagger CLI version to use (default: 0.15.1)
#   --dagger-cmd=CMD      Dagger command to run (default: "call build --src=.")
#   --help                Show this help message
#
# Examples:
#   ./ci-integration-setup.sh --ci=github
#   ./ci-integration-setup.sh --ci=all --dagger-version=0.15.1
#   ./ci-integration-setup.sh --ci=gitlab --out=./generated
#   ./ci-integration-setup.sh --ci=github --dagger-cmd="call ci --src=. --token=env:DEPLOY_TOKEN"
#

set -euo pipefail

CI_PLATFORM="all"
OUT_DIR="."
DAGGER_VERSION="0.15.1"
DAGGER_CMD="call build --src=."

for arg in "$@"; do
    case "$arg" in
        --ci=*)              CI_PLATFORM="${arg#*=}" ;;
        --out=*)             OUT_DIR="${arg#*=}" ;;
        --dagger-version=*)  DAGGER_VERSION="${arg#*=}" ;;
        --dagger-cmd=*)      DAGGER_CMD="${arg#*=}" ;;
        --help|-h)           sed -n '3,16p' "$0" | sed 's/^# \?//'; exit 0 ;;
        *)                   echo "Unknown option: $arg"; exit 1 ;;
    esac
done

# Split dagger command into verb and args for GitHub Actions format
DAGGER_VERB=$(echo "$DAGGER_CMD" | awk '{print $1}')
DAGGER_ARGS=$(echo "$DAGGER_CMD" | sed "s/^$DAGGER_VERB //")

generate_github() {
    local dir="$OUT_DIR/.github/workflows"
    mkdir -p "$dir"
    local file="$dir/dagger.yml"

    cat > "$file" <<YAML
# Generated by ci-integration-setup.sh
# Dagger CI pipeline for GitHub Actions
name: Dagger CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dagger:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Dagger Pipeline
        uses: dagger/dagger-for-github@v7
        with:
          verb: ${DAGGER_VERB}
          args: ${DAGGER_ARGS}
          version: "${DAGGER_VERSION}"
        env:
          # Add secrets as needed:
          # DEPLOY_TOKEN: \${{ secrets.DEPLOY_TOKEN }}
          # GHCR_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
YAML

    echo "✅ GitHub Actions: $file"
}

generate_gitlab() {
    local file="$OUT_DIR/.gitlab-ci.dagger.yml"

    cat > "$file" <<YAML
# Generated by ci-integration-setup.sh
# Dagger CI pipeline for GitLab CI
# Merge into your .gitlab-ci.yml or rename to .gitlab-ci.yml

stages:
  - ci

dagger:
  stage: ci
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DAGGER_VERSION: "${DAGGER_VERSION}"
  before_script:
    - apk add --no-cache curl
    - curl -fsSL https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=\${DAGGER_VERSION} sh
    - export PATH=\$PWD/bin:\$PATH
    - dagger version
  script:
    - dagger ${DAGGER_CMD}
  # Uncomment for specific branches:
  # rules:
  #   - if: \$CI_COMMIT_BRANCH == "main"
  #   - if: \$CI_PIPELINE_SOURCE == "merge_request_event"
YAML

    echo "✅ GitLab CI:      $file"
}

generate_circleci() {
    local dir="$OUT_DIR/.circleci"
    mkdir -p "$dir"
    local file="$dir/config.yml"

    cat > "$file" <<YAML
# Generated by ci-integration-setup.sh
# Dagger CI pipeline for CircleCI
version: 2.1

jobs:
  dagger:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Install Dagger
          command: |
            curl -fsSL https://dl.dagger.io/dagger/install.sh | DAGGER_VERSION=${DAGGER_VERSION} sh
            sudo mv ./bin/dagger /usr/local/bin/
            dagger version
      - run:
          name: Run Dagger Pipeline
          command: dagger ${DAGGER_CMD}
          # Add environment variables in CircleCI project settings
          # or uncomment below:
          # environment:
          #   DEPLOY_TOKEN: \${DEPLOY_TOKEN}

workflows:
  ci:
    jobs:
      - dagger:
          filters:
            branches:
              only:
                - main
                - /pull\/.*/
YAML

    echo "✅ CircleCI:       $file"
}

echo "🔧 Generating CI configurations (Dagger v${DAGGER_VERSION})"
echo "   Command: dagger ${DAGGER_CMD}"
echo ""

case "$CI_PLATFORM" in
    github)   generate_github ;;
    gitlab)   generate_gitlab ;;
    circleci) generate_circleci ;;
    all)
        generate_github
        generate_gitlab
        generate_circleci
        ;;
    *)
        echo "Error: Unknown CI platform '$CI_PLATFORM'. Choose: github, gitlab, circleci, all"
        exit 1
        ;;
esac

echo ""
echo "📝 Next steps:"
echo "   1. Review and customize the generated config(s)"
echo "   2. Add required secrets/variables in your CI platform settings"
echo "   3. Commit and push to trigger the pipeline"
echo "   4. Test locally first: dagger ${DAGGER_CMD}"
