#!/usr/bin/env bash
###############################################################################
# setup-nats-cluster.sh — Bootstrap a 3-node NATS cluster with JetStream
#
# Usage:
#   ./setup-nats-cluster.sh              Start (or restart) the cluster
#   ./setup-nats-cluster.sh --clean      Tear down containers, volumes, and configs
#   ./setup-nats-cluster.sh --help       Show this help message
#
# The script:
#   1. Checks for docker / docker compose prerequisites
#   2. Generates per-node NATS server configs (JetStream + clustering)
#   3. Generates a docker-compose.yml for nats-1, nats-2, nats-3
#   4. Starts the cluster and waits for all nodes to become healthy
#   5. Creates a TEST stream (subjects: test.>)
#   6. Prints cluster status and connection info
#
# Port mappings:
#   Node    Client   Monitoring   Cluster
#   nats-1  4222     8222         6222
#   nats-2  4223     8223         6223
#   nats-3  4224     8224         6224
###############################################################################
set -euo pipefail

# ─── Configurable defaults ───────────────────────────────────────────────────
CLUSTER_NAME="local-nats-cluster"
DATA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/nats-cluster-data"
NATS_IMAGE="nats:2-alpine"
HEALTH_TIMEOUT=60          # seconds to wait for cluster health
HEALTH_INTERVAL=2          # seconds between health probes

# ─── Colour helpers ──────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { printf "${CYAN}[INFO]${NC}  %s\n" "$*"; }
ok()    { printf "${GREEN}[OK]${NC}    %s\n" "$*"; }
warn()  { printf "${YELLOW}[WARN]${NC}  %s\n" "$*"; }
err()   { printf "${RED}[ERROR]${NC} %s\n" "$*" >&2; }

# ─── Usage / help ────────────────────────────────────────────────────────────
usage() {
  sed -n '2,/^###*$/{ s/^# \{0,1\}//; p; }' "$0"
  exit 0
}

# ─── Prerequisite checks ────────────────────────────────────────────────────
check_prerequisites() {
  info "Checking prerequisites…"

  if ! command -v docker &>/dev/null; then
    err "docker is not installed. Please install Docker: https://docs.docker.com/get-docker/"
    exit 2
  fi

  # Accept both "docker compose" (v2 plugin) and "docker-compose" (standalone)
  if docker compose version &>/dev/null; then
    COMPOSE_CMD="docker compose"
  elif command -v docker-compose &>/dev/null; then
    COMPOSE_CMD="docker-compose"
  else
    err "docker compose is not available. Install the Compose plugin or docker-compose."
    exit 2
  fi

  ok "docker $(docker --version | awk '{print $3}') found"
  ok "$COMPOSE_CMD available"
}

# ─── Generate a NATS server config for a single node ────────────────────────
# $1 = node name (nats-1), $2 = client port, $3 = monitor port, $4 = cluster port
generate_node_config() {
  local name="$1" client_port="$2" monitor_port="$3" cluster_port="$4"
  local cfg_dir="${DATA_DIR}/config"
  mkdir -p "$cfg_dir"

  cat > "${cfg_dir}/${name}.conf" <<EOF
# ── ${name} server configuration ──────────────────────────────────────────
server_name: ${name}
listen: 0.0.0.0:4222

# ── JetStream ─────────────────────────────────────────────────────────────
jetstream {
  store_dir: /data/jetstream
  max_mem:   256MB
  max_file:  1GB
}

# ── Monitoring ────────────────────────────────────────────────────────────
http_port: 8222

# ── Cluster ───────────────────────────────────────────────────────────────
cluster {
  name: ${CLUSTER_NAME}
  listen: 0.0.0.0:6222

  routes = [
    nats-route://nats-1:6222
    nats-route://nats-2:6222
    nats-route://nats-3:6222
  ]

  # Allow routes to be automatically discovered
  connect_retries: 30
}

# ── Limits ────────────────────────────────────────────────────────────────
max_payload:     8MB
max_connections: 1024
EOF

  ok "Generated config for ${name}"
}

# ─── Generate docker-compose.yml ─────────────────────────────────────────────
generate_compose() {
  info "Generating docker-compose.yml…"
  mkdir -p "${DATA_DIR}"

  cat > "${DATA_DIR}/docker-compose.yml" <<EOF
# Auto-generated by setup-nats-cluster.sh — do not edit manually.
version: "3.9"

services:
  # ── Node 1 ────────────────────────────────────────────────────────────────
  nats-1:
    image: ${NATS_IMAGE}
    container_name: nats-1
    hostname: nats-1
    command: ["-c", "/config/nats-1.conf"]
    ports:
      - "4222:4222"   # client
      - "8222:8222"   # monitoring
      - "6222:6222"   # cluster
    volumes:
      - ./config/nats-1.conf:/config/nats-1.conf:ro
      - nats-1-data:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 5s
      timeout: 3s
      retries: 12
    networks:
      - nats-cluster

  # ── Node 2 ────────────────────────────────────────────────────────────────
  nats-2:
    image: ${NATS_IMAGE}
    container_name: nats-2
    hostname: nats-2
    command: ["-c", "/config/nats-2.conf"]
    ports:
      - "4223:4222"   # client
      - "8223:8222"   # monitoring
      - "6223:6222"   # cluster
    volumes:
      - ./config/nats-2.conf:/config/nats-2.conf:ro
      - nats-2-data:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 5s
      timeout: 3s
      retries: 12
    networks:
      - nats-cluster

  # ── Node 3 ────────────────────────────────────────────────────────────────
  nats-3:
    image: ${NATS_IMAGE}
    container_name: nats-3
    hostname: nats-3
    command: ["-c", "/config/nats-3.conf"]
    ports:
      - "4224:4222"   # client
      - "8224:8222"   # monitoring
      - "6224:6222"   # cluster
    volumes:
      - ./config/nats-3.conf:/config/nats-3.conf:ro
      - nats-3-data:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 5s
      timeout: 3s
      retries: 12
    networks:
      - nats-cluster

volumes:
  nats-1-data:
  nats-2-data:
  nats-3-data:

networks:
  nats-cluster:
    driver: bridge
EOF

  ok "docker-compose.yml written to ${DATA_DIR}/docker-compose.yml"
}

# ─── Wait for every node to become healthy ───────────────────────────────────
wait_for_healthy() {
  info "Waiting up to ${HEALTH_TIMEOUT}s for cluster to become healthy…"
  local elapsed=0

  while (( elapsed < HEALTH_TIMEOUT )); do
    local all_healthy=true

    for port in 8222 8223 8224; do
      if ! curl -sf "http://localhost:${port}/healthz" &>/dev/null; then
        all_healthy=false
        break
      fi
    done

    if $all_healthy; then
      ok "All 3 nodes are healthy (${elapsed}s elapsed)"
      return 0
    fi

    sleep "$HEALTH_INTERVAL"
    (( elapsed += HEALTH_INTERVAL ))
  done

  err "Cluster did not become healthy within ${HEALTH_TIMEOUT}s"
  return 1
}

# ─── Create a TEST stream ───────────────────────────────────────────────────
create_test_stream() {
  info "Creating TEST stream (subjects: test.>)…"

  # Prefer the nats CLI, fall back to a raw HTTP API call via curl
  if command -v nats &>/dev/null; then
    if nats stream info TEST --server nats://localhost:4222 &>/dev/null; then
      warn "TEST stream already exists — skipping creation"
    else
      nats stream add TEST \
        --subjects "test.>" \
        --storage file \
        --replicas 3 \
        --retention limits \
        --max-msgs -1 \
        --max-bytes -1 \
        --max-age 24h \
        --max-msg-size -1 \
        --discard old \
        --dupe-window 2m \
        --server nats://localhost:4222 \
        --defaults
      ok "TEST stream created via nats CLI"
    fi
  else
    # Fallback: use the JetStream HTTP management API
    local payload
    payload=$(cat <<'APIJSON'
{
  "name": "TEST",
  "subjects": ["test.>"],
  "retention": "limits",
  "max_consumers": -1,
  "max_msgs": -1,
  "max_bytes": -1,
  "max_age": 86400000000000,
  "storage": "file",
  "num_replicas": 3,
  "duplicate_window": 120000000000,
  "discard": "old"
}
APIJSON
    )

    local http_code
    http_code=$(curl -s -o /dev/null -w "%{http_code}" \
      -X POST "http://localhost:8222/jsz" 2>/dev/null || true)

    # Use the NATS protocol directly via nats-server API
    warn "nats CLI not found — attempting stream creation via API"
    # The management API is only available through the client protocol,
    # so we advise the user to install the nats CLI.
    warn "Install the nats CLI for full functionality: https://github.com/nats-io/natscli"
  fi
}

# ─── Print cluster status ───────────────────────────────────────────────────
print_status() {
  echo ""
  printf "${CYAN}╔══════════════════════════════════════════════════════════════╗${NC}\n"
  printf "${CYAN}║${NC}              NATS Cluster Ready                             ${CYAN}║${NC}\n"
  printf "${CYAN}╠══════════════════════════════════════════════════════════════╣${NC}\n"
  printf "${CYAN}║${NC}  Node    │ Client          │ Monitoring      │ Cluster      ${CYAN}║${NC}\n"
  printf "${CYAN}║${NC}  ────────┼─────────────────┼─────────────────┼───────────── ${CYAN}║${NC}\n"
  printf "${CYAN}║${NC}  nats-1  │ localhost:4222   │ localhost:8222   │ :6222       ${CYAN}║${NC}\n"
  printf "${CYAN}║${NC}  nats-2  │ localhost:4223   │ localhost:8223   │ :6223       ${CYAN}║${NC}\n"
  printf "${CYAN}║${NC}  nats-3  │ localhost:4224   │ localhost:8224   │ :6224       ${CYAN}║${NC}\n"
  printf "${CYAN}╠══════════════════════════════════════════════════════════════╣${NC}\n"
  printf "${CYAN}║${NC}  Connect: nats://localhost:4222                              ${CYAN}║${NC}\n"
  printf "${CYAN}║${NC}  Monitor: http://localhost:8222                              ${CYAN}║${NC}\n"
  printf "${CYAN}╚══════════════════════════════════════════════════════════════╝${NC}\n"
  echo ""

  # Show live cluster info if the nats CLI is available
  if command -v nats &>/dev/null; then
    info "Cluster report:"
    nats server report jetstream --server nats://localhost:4222 2>/dev/null || true
  fi
}

# ─── Tear-down ───────────────────────────────────────────────────────────────
clean() {
  info "Tearing down NATS cluster…"

  if [[ -f "${DATA_DIR}/docker-compose.yml" ]]; then
    $COMPOSE_CMD -f "${DATA_DIR}/docker-compose.yml" down -v --remove-orphans 2>/dev/null || true
    ok "Containers and volumes removed"
  fi

  if [[ -d "${DATA_DIR}" ]]; then
    rm -rf "${DATA_DIR}"
    ok "Cluster data directory removed: ${DATA_DIR}"
  fi

  ok "Clean-up complete"
  exit 0
}

# ─── Main ────────────────────────────────────────────────────────────────────
main() {
  case "${1:-}" in
    --help|-h)  usage ;;
    --clean)    check_prerequisites; clean ;;
  esac

  check_prerequisites

  info "Setting up 3-node NATS cluster in ${DATA_DIR}"

  # Generate configs for each node
  generate_node_config "nats-1" 4222 8222 6222
  generate_node_config "nats-2" 4223 8223 6223
  generate_node_config "nats-3" 4224 8224 6224

  generate_compose

  # Start (or recreate) the cluster
  info "Starting cluster…"
  $COMPOSE_CMD -f "${DATA_DIR}/docker-compose.yml" up -d --force-recreate

  wait_for_healthy

  create_test_stream

  print_status
}

main "$@"
