#!/usr/bin/env bash
# vapor-docker-build.sh — Multi-stage Docker build for Vapor applications
set -euo pipefail

# ─── Configuration ───────────────────────────────────────────────
APP_NAME="${APP_NAME:-App}"
IMAGE_NAME="${IMAGE_NAME:-vapor-app}"
IMAGE_TAG="${IMAGE_TAG:-latest}"
SWIFT_VERSION="${SWIFT_VERSION:-5.9}"
UBUNTU_VERSION="${UBUNTU_VERSION:-jammy}"
PLATFORM="${PLATFORM:-linux/amd64}"
BUILD_ARGS="${BUILD_ARGS:---static-swift-stdlib}"
PARALLEL_JOBS="${PARALLEL_JOBS:-}"
PUSH="${PUSH:-false}"
REGISTRY="${REGISTRY:-}"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --name)     IMAGE_NAME="$2"; shift 2 ;;
        --tag)      IMAGE_TAG="$2"; shift 2 ;;
        --swift)    SWIFT_VERSION="$2"; shift 2 ;;
        --platform) PLATFORM="$2"; shift 2 ;;
        --jobs)     PARALLEL_JOBS="$2"; shift 2 ;;
        --push)     PUSH="true"; shift ;;
        --registry) REGISTRY="$2"; shift 2 ;;
        --help)
            echo "Usage: $0 [options]"
            echo "  --name NAME       Docker image name (default: vapor-app)"
            echo "  --tag TAG         Docker image tag (default: latest)"
            echo "  --swift VERSION   Swift version (default: 5.9)"
            echo "  --platform PLAT   Target platform (default: linux/amd64)"
            echo "  --jobs N          Parallel compilation jobs"
            echo "  --push            Push image after build"
            echo "  --registry URL    Container registry URL"
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

FULL_IMAGE="${IMAGE_NAME}:${IMAGE_TAG}"
if [ -n "${REGISTRY}" ]; then
    FULL_IMAGE="${REGISTRY}/${FULL_IMAGE}"
fi

echo "╔══════════════════════════════════════════════════╗"
echo "║  Vapor Docker Build                             ║"
echo "╚══════════════════════════════════════════════════╝"
echo "Image:      ${FULL_IMAGE}"
echo "Swift:      ${SWIFT_VERSION}"
echo "Platform:   ${PLATFORM}"
echo ""

# ─── Verify Project Structure ───────────────────────────────────
if [ ! -f "Package.swift" ]; then
    echo "❌ Package.swift not found. Run this from the project root."
    exit 1
fi

# ─── Generate Dockerfile if missing ─────────────────────────────
DOCKERFILE="Dockerfile"
if [ ! -f "${DOCKERFILE}" ]; then
    echo "==> No Dockerfile found. Generating multi-stage Dockerfile..."

    JOBS_FLAG=""
    if [ -n "${PARALLEL_JOBS}" ]; then
        JOBS_FLAG="-j ${PARALLEL_JOBS}"
    fi

    cat > "${DOCKERFILE}" << EOF
# ══════════════════════════════════════════════════════
# Multi-stage Dockerfile for Vapor 4.x
# Generated by vapor-docker-build.sh
# ══════════════════════════════════════════════════════

# ── Stage 1: Build ──
FROM swift:${SWIFT_VERSION}-${UBUNTU_VERSION} AS build
WORKDIR /build

# Resolve dependencies first (better layer caching)
COPY Package.swift Package.resolved* ./
RUN swift package resolve

# Copy source and build
COPY . .
RUN swift build -c release ${BUILD_ARGS} ${JOBS_FLAG}

# Verify binary exists
RUN test -f .build/release/${APP_NAME} || (echo "❌ Binary not found at .build/release/${APP_NAME}" && exit 1)

# ── Stage 2: Runtime ──
FROM ubuntu:${UBUNTU_VERSION} AS runtime

# Create non-root user
RUN groupadd -r vapor && useradd -r -g vapor -m vapor

# Install only runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    libcurl4 \\
    libxml2 \\
    tzdata \\
    ca-certificates \\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy built binary
COPY --from=build /build/.build/release/${APP_NAME} .

# Copy static assets if they exist
COPY --from=build /build/Public ./Public
COPY --from=build /build/Resources ./Resources

# Set ownership
RUN chown -R vapor:vapor /app

USER vapor
EXPOSE 8080

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \\
    CMD curl -f http://localhost:8080/health || exit 1

ENTRYPOINT ["./${APP_NAME}", "serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
EOF
    echo "✅ Dockerfile generated"
fi

# ─── Build ───────────────────────────────────────────────────────
echo "==> Building Docker image..."
BUILD_START=$(date +%s)

DOCKER_BUILDKIT=1 docker build \
    --platform "${PLATFORM}" \
    --tag "${FULL_IMAGE}" \
    --build-arg SWIFT_VERSION="${SWIFT_VERSION}" \
    --progress=plain \
    -f "${DOCKERFILE}" \
    .

BUILD_END=$(date +%s)
BUILD_DURATION=$((BUILD_END - BUILD_START))

echo ""
echo "✅ Build complete in ${BUILD_DURATION}s"
echo "   Image: ${FULL_IMAGE}"

# ─── Image Info ──────────────────────────────────────────────────
echo ""
echo "==> Image details:"
docker images "${IMAGE_NAME}:${IMAGE_TAG}" --format "   Size: {{.Size}}"
docker images "${IMAGE_NAME}:${IMAGE_TAG}" --format "   Created: {{.CreatedSince}}"

# ─── Push ────────────────────────────────────────────────────────
if [ "${PUSH}" = "true" ]; then
    echo ""
    echo "==> Pushing image to registry..."
    docker push "${FULL_IMAGE}"
    echo "✅ Pushed: ${FULL_IMAGE}"
fi

echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║  Done! Run with:                                ║"
echo "║  docker run -p 8080:8080 ${FULL_IMAGE}           "
echo "╚══════════════════════════════════════════════════╝"
