#!/usr/bin/env bash
# =============================================================================
# generate-crud.sh — Generate a TypeScript CRUD service for a Prisma model
#
# Usage:
#   ./generate-crud.sh <ModelName> [output-dir]
#
# Arguments:
#   ModelName    PascalCase model name (e.g., User, BlogPost, OrderItem)
#   output-dir   Directory for the generated file (default: ./src/services)
#
# Examples:
#   ./generate-crud.sh User
#   ./generate-crud.sh BlogPost ./src/modules/blog
#   ./generate-crud.sh OrderItem ./src/services
#
# Generates:
#   A TypeScript service file with: findMany (paginated), findUnique,
#   create, update, delete, and count operations.
# =============================================================================
set -euo pipefail

MODEL_NAME="${1:?Usage: $0 <ModelName> [output-dir]}"
OUTPUT_DIR="${2:-./src/services}"

# Derive names
# camelCase: first letter lowercase
CAMEL_NAME="$(echo "${MODEL_NAME:0:1}" | tr '[:upper:]' '[:lower:]')${MODEL_NAME:1}"
# kebab-case: insert hyphens before uppercase letters, then lowercase
KEBAB_NAME="$(echo "$MODEL_NAME" | sed 's/\([A-Z]\)/-\1/g' | sed 's/^-//' | tr '[:upper:]' '[:lower:]')"
FILE_NAME="${KEBAB_NAME}.service.ts"

mkdir -p "$OUTPUT_DIR"
OUTPUT_PATH="$OUTPUT_DIR/$FILE_NAME"

if [ -f "$OUTPUT_PATH" ]; then
  echo "⚠️  File already exists: $OUTPUT_PATH"
  read -r -p "Overwrite? [y/N] " confirm
  if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
  fi
fi

cat > "$OUTPUT_PATH" << SERVICE
import { PrismaClient, Prisma } from '@prisma/client';

const prisma = new PrismaClient();

// ============================================================================
// ${MODEL_NAME} CRUD Service
// Generated by generate-crud.sh
// ============================================================================

export interface PaginationParams {
  page?: number;
  pageSize?: number;
  orderBy?: Prisma.${MODEL_NAME}OrderByWithRelationInput;
}

export interface PaginatedResult<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

/**
 * Find many ${CAMEL_NAME}s with pagination, filtering, and sorting.
 */
export async function findMany${MODEL_NAME}s(
  where?: Prisma.${MODEL_NAME}WhereInput,
  params: PaginationParams = {}
): Promise<PaginatedResult<Prisma.${MODEL_NAME}GetPayload<{}>>> {
  const { page = 1, pageSize = 20, orderBy = { id: 'desc' } } = params;
  const skip = (page - 1) * pageSize;

  const [data, total] = await prisma.\$transaction([
    prisma.${CAMEL_NAME}.findMany({
      where,
      skip,
      take: pageSize,
      orderBy,
    }),
    prisma.${CAMEL_NAME}.count({ where }),
  ]);

  return {
    data,
    total,
    page,
    pageSize,
    totalPages: Math.ceil(total / pageSize),
  };
}

/**
 * Find a single ${CAMEL_NAME} by unique identifier.
 * Returns null if not found.
 */
export async function find${MODEL_NAME}ById(
  id: number,
  include?: Prisma.${MODEL_NAME}Include
) {
  return prisma.${CAMEL_NAME}.findUnique({
    where: { id },
    ...(include && { include }),
  });
}

/**
 * Find a single ${CAMEL_NAME} by unique identifier.
 * Throws if not found.
 */
export async function find${MODEL_NAME}ByIdOrThrow(
  id: number,
  include?: Prisma.${MODEL_NAME}Include
) {
  return prisma.${CAMEL_NAME}.findUniqueOrThrow({
    where: { id },
    ...(include && { include }),
  });
}

/**
 * Create a new ${CAMEL_NAME}.
 */
export async function create${MODEL_NAME}(
  data: Prisma.${MODEL_NAME}CreateInput,
  include?: Prisma.${MODEL_NAME}Include
) {
  return prisma.${CAMEL_NAME}.create({
    data,
    ...(include && { include }),
  });
}

/**
 * Update an existing ${CAMEL_NAME} by ID.
 */
export async function update${MODEL_NAME}(
  id: number,
  data: Prisma.${MODEL_NAME}UpdateInput,
  include?: Prisma.${MODEL_NAME}Include
) {
  return prisma.${CAMEL_NAME}.update({
    where: { id },
    data,
    ...(include && { include }),
  });
}

/**
 * Delete a ${CAMEL_NAME} by ID.
 */
export async function delete${MODEL_NAME}(id: number) {
  return prisma.${CAMEL_NAME}.delete({
    where: { id },
  });
}

/**
 * Count ${CAMEL_NAME}s matching optional filter.
 */
export async function count${MODEL_NAME}s(
  where?: Prisma.${MODEL_NAME}WhereInput
): Promise<number> {
  return prisma.${CAMEL_NAME}.count({ where });
}

/**
 * Upsert: create if not exists, update if exists.
 * Requires a unique field for the where clause.
 */
export async function upsert${MODEL_NAME}(
  where: Prisma.${MODEL_NAME}WhereUniqueInput,
  create: Prisma.${MODEL_NAME}CreateInput,
  update: Prisma.${MODEL_NAME}UpdateInput,
  include?: Prisma.${MODEL_NAME}Include
) {
  return prisma.${CAMEL_NAME}.upsert({
    where,
    create,
    update,
    ...(include && { include }),
  });
}
SERVICE

echo "✅ Generated: $OUTPUT_PATH"
echo ""
echo "Usage in your code:"
echo ""
echo "  import {"
echo "    findMany${MODEL_NAME}s,"
echo "    find${MODEL_NAME}ById,"
echo "    create${MODEL_NAME},"
echo "    update${MODEL_NAME},"
echo "    delete${MODEL_NAME},"
echo "    count${MODEL_NAME}s,"
echo "  } from './${KEBAB_NAME}.service';"
echo ""
