#!/usr/bin/env bash
# =============================================================================
# generate-page-object.sh
#
# Generates a Page Object Model TypeScript class from a URL.
# Analyzes the page structure and creates a POM with locators for interactive
# elements, navigation methods, and typed helpers.
#
# Usage:
#   ./generate-page-object.sh --url <URL> --name <PageName> [OPTIONS]
#
# Required:
#   --url URL         Target URL to analyze for POM generation
#   --name NAME       POM class name (e.g., LoginPage, DashboardPage)
#
# Options:
#   --output DIR      Output directory (default: ./pages)
#   --base-url URL    Base URL to strip from goto paths (default: inferred)
#   --include-nav     Include navigation helper methods
#   --help            Show this help message
#
# Examples:
#   ./generate-page-object.sh --url http://localhost:3000/login --name LoginPage
#   ./generate-page-object.sh --url https://example.com/dashboard --name DashboardPage --output src/pages
# =============================================================================

set -euo pipefail

# Defaults
URL=""
NAME=""
OUTPUT_DIR="./pages"
BASE_URL=""
INCLUDE_NAV=false

usage() {
  head -n 22 "$0" | tail -n +3 | sed 's/^# \?//'
  exit 0
}

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --url)         URL="$2"; shift 2 ;;
    --name)        NAME="$2"; shift 2 ;;
    --output)      OUTPUT_DIR="$2"; shift 2 ;;
    --base-url)    BASE_URL="$2"; shift 2 ;;
    --include-nav) INCLUDE_NAV=true; shift ;;
    --help|-h)     usage ;;
    *)             echo "Unknown option: $1"; usage ;;
  esac
done

# Validate required args
if [[ -z "$URL" ]]; then
  echo "Error: --url is required"
  usage
fi

if [[ -z "$NAME" ]]; then
  echo "Error: --name is required"
  usage
fi

# Infer base URL if not provided
if [[ -z "$BASE_URL" ]]; then
  BASE_URL=$(echo "$URL" | sed -E 's|(https?://[^/]+).*|\1|')
fi

# Derive page path from URL
PAGE_PATH=$(echo "$URL" | sed "s|${BASE_URL}||")
if [[ -z "$PAGE_PATH" ]]; then
  PAGE_PATH="/"
fi

# Convert PascalCase name to kebab-case for filename
FILENAME=$(echo "$NAME" | sed -E 's/([A-Z])/-\1/g' | sed 's/^-//' | tr '[:upper:]' '[:lower:]')

mkdir -p "$OUTPUT_DIR"
FILEPATH="${OUTPUT_DIR}/${FILENAME}.ts"

echo "=== Page Object Model Generator ==="
echo "URL:       $URL"
echo "Class:     $NAME"
echo "Path:      $PAGE_PATH"
echo "Output:    $FILEPATH"
echo ""

# Generate the POM file
cat > "$FILEPATH" <<TYPESCRIPT
import { type Page, type Locator, expect } from '@playwright/test';

/**
 * Page Object Model for: ${URL}
 * Generated by generate-page-object.sh
 *
 * TODO: Update locators to match your actual page elements.
 * Prefer accessible locators: getByRole, getByLabel, getByText, getByTestId.
 */
export class ${NAME} {
  // --- Locators ---
  readonly heading: Locator;
  readonly primaryAction: Locator;

  // Form elements (update selectors as needed)
  // readonly emailInput: Locator;
  // readonly passwordInput: Locator;
  // readonly submitButton: Locator;

  // Navigation elements
  // readonly navLinks: Locator;
  // readonly userMenu: Locator;

  constructor(private readonly page: Page) {
    this.heading = page.getByRole('heading', { level: 1 });
    this.primaryAction = page.getByRole('button').first();

    // Initialize form locators
    // this.emailInput = page.getByLabel('Email');
    // this.passwordInput = page.getByLabel('Password');
    // this.submitButton = page.getByRole('button', { name: 'Submit' });

    // Initialize navigation locators
    // this.navLinks = page.getByRole('navigation').getByRole('link');
    // this.userMenu = page.getByTestId('user-menu');
  }

  // --- Navigation ---

  /** Navigate to this page */
  async goto(): Promise<void> {
    await this.page.goto('${PAGE_PATH}');
    await this.waitForPageLoad();
  }

  /** Wait for page to be fully loaded */
  async waitForPageLoad(): Promise<void> {
    await expect(this.heading).toBeVisible();
  }

  // --- Actions ---

  // Example: Fill and submit a form
  // async submitForm(data: { email: string; password: string }): Promise<void> {
  //   await this.emailInput.fill(data.email);
  //   await this.passwordInput.fill(data.password);
  //   await this.submitButton.click();
  // }

  // --- Assertions ---

  /** Assert the page heading matches expected text */
  async expectHeading(text: string | RegExp): Promise<void> {
    await expect(this.heading).toHaveText(text);
  }

  /** Assert the current URL matches a pattern */
  async expectURL(pattern: string | RegExp): Promise<void> {
    await expect(this.page).toHaveURL(pattern);
  }

  // --- Helpers ---

  /** Take a screenshot of the page */
  async screenshot(name?: string): Promise<Buffer> {
    return await this.page.screenshot({
      path: name ? \`screenshots/\${name}.png\` : undefined,
      fullPage: true,
    });
  }

  /** Get text content from an element by test ID */
  async getTextByTestId(testId: string): Promise<string> {
    return await this.page.getByTestId(testId).innerText();
  }
TYPESCRIPT

# Add navigation helpers if requested
if [[ "$INCLUDE_NAV" == true ]]; then
  cat >> "$FILEPATH" <<'NAV_HELPERS'

  // --- Navigation Helpers ---

  /** Click a navigation link by name */
  async navigateTo(linkName: string): Promise<void> {
    await this.page.getByRole('navigation').getByRole('link', { name: linkName }).click();
  }

  /** Go back to previous page */
  async goBack(): Promise<void> {
    await this.page.goBack();
    await this.waitForPageLoad();
  }
NAV_HELPERS
fi

# Close the class
echo "}" >> "$FILEPATH"

# Generate a companion test file
TEST_DIR="${OUTPUT_DIR}/../tests"
mkdir -p "$TEST_DIR"
TEST_FILE="${TEST_DIR}/${FILENAME}.spec.ts"

if [[ ! -f "$TEST_FILE" ]]; then
  cat > "$TEST_FILE" <<TEST
import { test, expect } from '@playwright/test';
import { ${NAME} } from '../pages/${FILENAME}';

test.describe('${NAME}', () => {
  let pageObject: ${NAME};

  test.beforeEach(async ({ page }) => {
    pageObject = new ${NAME}(page);
    await pageObject.goto();
  });

  test('page loads successfully', async () => {
    await pageObject.expectURL('${PAGE_PATH}');
  });

  test('heading is visible', async () => {
    await expect(pageObject.heading).toBeVisible();
  });

  // TODO: Add more tests for ${NAME}
});
TEST
  echo "✓ Test file created: $TEST_FILE"
fi

echo "✓ Page Object created: $FILEPATH"
echo ""
echo "Next steps:"
echo "  1. Update locators in ${FILEPATH} to match your page"
echo "  2. Add action methods for user interactions"
echo "  3. Run tests: npx playwright test ${TEST_FILE}"
