#!/usr/bin/env bash
# makefile-init.sh — Generate a Makefile template for a given project type.
#
# Usage:
#   makefile-init.sh <type> [output]
#
# Types: go, node, python, docker, c, cpp
#
# Examples:
#   makefile-init.sh go                  # Write Makefile to stdout
#   makefile-init.sh python Makefile     # Write to ./Makefile
#   makefile-init.sh node -              # Write to stdout explicitly

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
    cat <<'EOF'
Usage: makefile-init.sh <type> [output]

Generate a production-ready Makefile template for the specified project type.

Types:
  go       Go project (build, test, lint, docker, release)
  node     Node.js project (install, build, test, lint, docker)
  python   Python project (venv, install, test, lint, format, docker)
  docker   Docker-based workflows (build, push, run, compose)
  c        C project (compile, link, test, clean)
  cpp      C++ project (compile, link, test, clean)

Options:
  output   Output file path (default: stdout, use - for stdout)

Examples:
  makefile-init.sh go
  makefile-init.sh python Makefile
  makefile-init.sh node ./build/Makefile
EOF
    exit "${1:-0}"
}

generate_go() {
    cat <<'MAKEFILE'
# Go Project Makefile
# Generated by makefile-init.sh

.DEFAULT_GOAL := help
.DELETE_ON_ERROR:
.SUFFIXES:

# ─── Configuration ──────────────────────────────────────────
BINARY     := $(shell basename $(CURDIR))
VERSION    := $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
COMMIT     := $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
BUILD_TIME := $(shell date -u +%Y-%m-%dT%H:%M:%SZ)
LDFLAGS    := -s -w \
    -X main.version=$(VERSION) \
    -X main.commit=$(COMMIT) \
    -X main.buildTime=$(BUILD_TIME)

GOFILES    := $(shell find . -name '*.go' -not -path './vendor/*')
GOPACKAGES := ./...

# Docker
IMAGE      := $(BINARY)
REGISTRY   ?= ghcr.io/$(shell git config user.name 2>/dev/null || echo myorg)
DOCKER_TAG := $(VERSION)

# ─── Targets ────────────────────────────────────────────────
.PHONY: all build run test test-race test-cover lint fmt vet tidy \
        docker docker-push clean help

all: lint test build ## Build after linting and testing

build: ## Build binary
	CGO_ENABLED=0 go build -ldflags '$(LDFLAGS)' -o bin/$(BINARY) ./cmd/$(BINARY)

run: build ## Build and run
	./bin/$(BINARY)

test: ## Run tests
	go test -count=1 $(GOPACKAGES)

test-race: ## Run tests with race detector
	go test -race -count=1 $(GOPACKAGES)

test-cover: ## Run tests with coverage report
	go test -race -coverprofile=coverage.out -covermode=atomic $(GOPACKAGES)
	go tool cover -html=coverage.out -o coverage.html
	@echo "Coverage report: coverage.html"

lint: ## Run golangci-lint
	golangci-lint run --timeout 5m $(GOPACKAGES)

fmt: ## Format code
	gofmt -s -w $(GOFILES)
	goimports -w $(GOFILES)

vet: ## Run go vet
	go vet $(GOPACKAGES)

tidy: ## Tidy and verify dependencies
	go mod tidy
	go mod verify

docker: ## Build Docker image
	docker build \
		--build-arg VERSION=$(VERSION) \
		--build-arg COMMIT=$(COMMIT) \
		-t $(REGISTRY)/$(IMAGE):$(DOCKER_TAG) \
		-t $(REGISTRY)/$(IMAGE):latest .

docker-push: docker ## Push Docker image to registry
	docker push $(REGISTRY)/$(IMAGE):$(DOCKER_TAG)
	docker push $(REGISTRY)/$(IMAGE):latest

clean: ## Remove build artifacts
	rm -rf bin/ dist/ coverage.out coverage.html

help: ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'
MAKEFILE
}

generate_node() {
    cat <<'MAKEFILE'
# Node.js Project Makefile
# Generated by makefile-init.sh

.DEFAULT_GOAL := help
.DELETE_ON_ERROR:
.SUFFIXES:

# ─── Configuration ──────────────────────────────────────────
APP_NAME   := $(shell node -p "require('./package.json').name" 2>/dev/null || basename $(CURDIR))
VERSION    := $(shell node -p "require('./package.json').version" 2>/dev/null || echo 0.0.0)
NODE_ENV   ?= development

# Sentinel file to track installed dependencies
NODE_MODULES := node_modules/.package-lock.json

# Docker
IMAGE      := $(APP_NAME)
REGISTRY   ?= ghcr.io/myorg
DOCKER_TAG := $(VERSION)

# ─── Targets ────────────────────────────────────────────────
.PHONY: all build dev test test-watch test-coverage lint lint-fix fmt \
        typecheck docker docker-push clean distclean help

all: lint test build ## Lint, test, and build

$(NODE_MODULES): package.json package-lock.json
	npm ci
	@touch $@

install: $(NODE_MODULES) ## Install dependencies

build: $(NODE_MODULES) ## Build for production
	NODE_ENV=production npm run build

dev: $(NODE_MODULES) ## Start development server
	npm run dev

test: $(NODE_MODULES) ## Run test suite
	npm test

test-watch: $(NODE_MODULES) ## Run tests in watch mode
	npm test -- --watch

test-coverage: $(NODE_MODULES) ## Run tests with coverage
	npm test -- --coverage
	@echo "Coverage report: coverage/lcov-report/index.html"

lint: $(NODE_MODULES) ## Run linter
	npm run lint

lint-fix: $(NODE_MODULES) ## Run linter with auto-fix
	npm run lint -- --fix

fmt: $(NODE_MODULES) ## Format code with prettier
	npx prettier --write "src/**/*.{js,ts,jsx,tsx,json,css,md}"

typecheck: $(NODE_MODULES) ## Run TypeScript type checker
	npx tsc --noEmit

docker: ## Build Docker image
	docker build \
		--build-arg NODE_ENV=production \
		-t $(REGISTRY)/$(IMAGE):$(DOCKER_TAG) \
		-t $(REGISTRY)/$(IMAGE):latest .

docker-push: docker ## Push Docker image to registry
	docker push $(REGISTRY)/$(IMAGE):$(DOCKER_TAG)
	docker push $(REGISTRY)/$(IMAGE):latest

clean: ## Remove build artifacts
	rm -rf dist/ build/ .next/ .cache/ coverage/ .parcel-cache/

distclean: clean ## Remove everything including node_modules
	rm -rf node_modules/

help: ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'
MAKEFILE
}

generate_python() {
    cat <<'MAKEFILE'
# Python Project Makefile
# Generated by makefile-init.sh

.DEFAULT_GOAL := help
.DELETE_ON_ERROR:
.SUFFIXES:

# ─── Configuration ──────────────────────────────────────────
PROJECT    := $(shell basename $(CURDIR))
PYTHON     := python3
VENV       := .venv
BIN        := $(VENV)/bin
PIP        := $(BIN)/pip
PYTEST     := $(BIN)/pytest
RUFF       := $(BIN)/ruff
MYPY       := $(BIN)/mypy

# Source directories
SRC_DIR    := src
TEST_DIR   := tests

# Docker
IMAGE      := $(PROJECT)
REGISTRY   ?= ghcr.io/myorg
VERSION    := $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)

# ─── Targets ────────────────────────────────────────────────
.PHONY: all install test test-watch test-coverage lint lint-fix fmt typecheck \
        docker docker-push clean distclean help

all: lint test ## Lint and test

$(VENV)/bin/activate: requirements.txt
	$(PYTHON) -m venv $(VENV)
	$(PIP) install --upgrade pip setuptools wheel
	$(PIP) install -r requirements.txt
	@touch $@

venv: $(VENV)/bin/activate ## Create virtual environment

install: $(VENV)/bin/activate ## Install dependencies
	$(PIP) install -e ".[dev]" 2>/dev/null || $(PIP) install -r requirements.txt

test: $(VENV)/bin/activate ## Run tests
	$(PYTEST) $(TEST_DIR)/ -v

test-watch: $(VENV)/bin/activate ## Run tests in watch mode
	$(PYTEST) $(TEST_DIR)/ -v --watch 2>/dev/null || \
		$(BIN)/ptw -- $(TEST_DIR)/ -v

test-coverage: $(VENV)/bin/activate ## Run tests with coverage
	$(PYTEST) $(TEST_DIR)/ -v --cov=$(SRC_DIR) --cov-report=html --cov-report=term
	@echo "Coverage report: htmlcov/index.html"

lint: $(VENV)/bin/activate ## Run linters
	$(RUFF) check $(SRC_DIR)/ $(TEST_DIR)/
	$(MYPY) $(SRC_DIR)/ --ignore-missing-imports

lint-fix: $(VENV)/bin/activate ## Run linter with auto-fix
	$(RUFF) check --fix $(SRC_DIR)/ $(TEST_DIR)/

fmt: $(VENV)/bin/activate ## Format code
	$(RUFF) format $(SRC_DIR)/ $(TEST_DIR)/

typecheck: $(VENV)/bin/activate ## Run type checker
	$(MYPY) $(SRC_DIR)/ --ignore-missing-imports

docker: ## Build Docker image
	docker build \
		--build-arg VERSION=$(VERSION) \
		-t $(REGISTRY)/$(IMAGE):$(VERSION) \
		-t $(REGISTRY)/$(IMAGE):latest .

docker-push: docker ## Push Docker image to registry
	docker push $(REGISTRY)/$(IMAGE):$(VERSION)
	docker push $(REGISTRY)/$(IMAGE):latest

clean: ## Remove build artifacts
	find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	find . -type d -name '*.egg-info' -exec rm -rf {} + 2>/dev/null || true
	rm -rf .pytest_cache/ .mypy_cache/ .ruff_cache/ htmlcov/ dist/ build/
	rm -f .coverage coverage.xml

distclean: clean ## Remove everything including venv
	rm -rf $(VENV)

help: ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'
MAKEFILE
}

generate_docker() {
    cat <<'MAKEFILE'
# Docker Workflow Makefile
# Generated by makefile-init.sh

.DEFAULT_GOAL := help
.DELETE_ON_ERROR:
.SUFFIXES:

# ─── Configuration ──────────────────────────────────────────
IMAGE      := $(shell basename $(CURDIR))
REGISTRY   ?= ghcr.io/myorg
VERSION    := $(shell git describe --tags --always --dirty 2>/dev/null || echo dev)
COMMIT     := $(shell git rev-parse --short HEAD 2>/dev/null || echo unknown)
DOCKER_TAG := $(VERSION)

# Compose
COMPOSE    := docker compose
COMPOSE_FILE ?= docker-compose.yml

# Build options
DOCKER_BUILD_ARGS := \
    --build-arg VERSION=$(VERSION) \
    --build-arg COMMIT=$(COMMIT) \
    --build-arg BUILD_TIME=$(shell date -u +%Y-%m-%dT%H:%M:%SZ)

PLATFORMS  ?= linux/amd64,linux/arm64

# ─── Targets ────────────────────────────────────────────────
.PHONY: build push pull run stop logs shell tag release \
        compose-up compose-down compose-logs compose-ps compose-restart \
        buildx-setup buildx clean prune help

build: ## Build Docker image
	docker build $(DOCKER_BUILD_ARGS) \
		-t $(REGISTRY)/$(IMAGE):$(DOCKER_TAG) \
		-t $(REGISTRY)/$(IMAGE):latest .

push: build ## Push image to registry
	docker push $(REGISTRY)/$(IMAGE):$(DOCKER_TAG)
	docker push $(REGISTRY)/$(IMAGE):latest

pull: ## Pull latest image from registry
	docker pull $(REGISTRY)/$(IMAGE):latest

run: ## Run container locally
	docker run --rm -it \
		--name $(IMAGE) \
		-p 8080:8080 \
		--env-file .env 2>/dev/null; \
	docker run --rm -it \
		--name $(IMAGE) \
		-p 8080:8080 \
		$(REGISTRY)/$(IMAGE):$(DOCKER_TAG)

stop: ## Stop running container
	docker stop $(IMAGE) 2>/dev/null || true

logs: ## Show container logs
	docker logs -f $(IMAGE)

shell: ## Open shell in running container
	docker exec -it $(IMAGE) /bin/sh

tag: ## Tag image with specific version (usage: make tag TAG=v1.2.3)
	docker tag $(REGISTRY)/$(IMAGE):$(DOCKER_TAG) $(REGISTRY)/$(IMAGE):$(TAG)

# ─── Compose ────────────────────────────────────────────────

compose-up: ## Start all services
	$(COMPOSE) -f $(COMPOSE_FILE) up -d

compose-down: ## Stop all services
	$(COMPOSE) -f $(COMPOSE_FILE) down

compose-logs: ## Show logs for all services
	$(COMPOSE) -f $(COMPOSE_FILE) logs -f

compose-ps: ## Show running services
	$(COMPOSE) -f $(COMPOSE_FILE) ps

compose-restart: ## Restart all services
	$(COMPOSE) -f $(COMPOSE_FILE) restart

# ─── Multi-Platform ─────────────────────────────────────────

buildx-setup: ## Set up Docker buildx for multi-platform builds
	docker buildx create --name multiplatform --use 2>/dev/null || \
		docker buildx use multiplatform
	docker buildx inspect --bootstrap

buildx: buildx-setup ## Build multi-platform image and push
	docker buildx build $(DOCKER_BUILD_ARGS) \
		--platform $(PLATFORMS) \
		-t $(REGISTRY)/$(IMAGE):$(DOCKER_TAG) \
		-t $(REGISTRY)/$(IMAGE):latest \
		--push .

# ─── Cleanup ────────────────────────────────────────────────

clean: stop ## Remove project images
	docker rmi $(REGISTRY)/$(IMAGE):$(DOCKER_TAG) 2>/dev/null || true
	docker rmi $(REGISTRY)/$(IMAGE):latest 2>/dev/null || true

prune: ## Remove all dangling images and build cache
	docker image prune -f
	docker builder prune -f

help: ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-18s\033[0m %s\n", $$1, $$2}'
MAKEFILE
}

generate_c() {
    cat <<'MAKEFILE'
# C Project Makefile
# Generated by makefile-init.sh

.DEFAULT_GOAL := help
.DELETE_ON_ERROR:
.SUFFIXES:

# ─── Configuration ──────────────────────────────────────────
TARGET   := app
CC       ?= gcc
CFLAGS   := -std=c11 -Wall -Wextra -Wpedantic -O2
LDFLAGS  :=
LDLIBS   :=

SRC_DIR  := src
INC_DIR  := include
BUILD_DIR := build

SRCS     := $(wildcard $(SRC_DIR)/*.c)
OBJS     := $(SRCS:$(SRC_DIR)/%.c=$(BUILD_DIR)/%.o)
DEPS     := $(OBJS:.o=.d)

DEPFLAGS  = -MMD -MP -MF $(@:.o=.d)

# ─── Targets ────────────────────────────────────────────────
.PHONY: all debug release test clean help

all: $(BUILD_DIR)/$(TARGET) ## Build the project

$(BUILD_DIR)/$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $^ $(LDLIBS)

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)
	$(CC) $(CFLAGS) $(DEPFLAGS) -I$(INC_DIR) -c $< -o $@

$(BUILD_DIR):
	mkdir -p $@

debug: CFLAGS := -std=c11 -Wall -Wextra -g -O0 -DDEBUG
debug: clean all ## Build with debug symbols

release: CFLAGS += -DNDEBUG -flto
release: LDFLAGS += -flto
release: all ## Build optimized release

test: $(BUILD_DIR)/$(TARGET) ## Run tests
	@echo "Running tests..."
	./$(BUILD_DIR)/$(TARGET) --test 2>/dev/null || echo "Add test framework"

clean: ## Remove build artifacts
	rm -rf $(BUILD_DIR)

-include $(DEPS)

help: ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'
MAKEFILE
}

generate_cpp() {
    cat <<'MAKEFILE'
# C++ Project Makefile
# Generated by makefile-init.sh

.DEFAULT_GOAL := help
.DELETE_ON_ERROR:
.SUFFIXES:

# ─── Configuration ──────────────────────────────────────────
TARGET   := app
CXX      ?= g++
CXXFLAGS := -std=c++17 -Wall -Wextra -Wpedantic -O2
LDFLAGS  :=
LDLIBS   :=

SRC_DIR   := src
INC_DIR   := include
BUILD_DIR := build

SRCS     := $(wildcard $(SRC_DIR)/*.cpp)
OBJS     := $(SRCS:$(SRC_DIR)/%.cpp=$(BUILD_DIR)/%.o)
DEPS     := $(OBJS:.o=.d)

DEPFLAGS  = -MMD -MP -MF $(@:.o=.d)

# ─── Targets ────────────────────────────────────────────────
.PHONY: all debug release test clean help

all: $(BUILD_DIR)/$(TARGET) ## Build the project

$(BUILD_DIR)/$(TARGET): $(OBJS)
	$(CXX) $(LDFLAGS) -o $@ $^ $(LDLIBS)

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.cpp | $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) $(DEPFLAGS) -I$(INC_DIR) -c $< -o $@

$(BUILD_DIR):
	mkdir -p $@

debug: CXXFLAGS := -std=c++17 -Wall -Wextra -g -O0 -DDEBUG
debug: clean all ## Build with debug symbols

release: CXXFLAGS += -DNDEBUG -flto
release: LDFLAGS += -flto
release: all ## Build optimized release

test: $(BUILD_DIR)/$(TARGET) ## Run tests
	@echo "Running tests..."
	./$(BUILD_DIR)/$(TARGET) --test 2>/dev/null || echo "Add test framework"

clean: ## Remove build artifacts
	rm -rf $(BUILD_DIR)

-include $(DEPS)

help: ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'
MAKEFILE
}

# ─── Main ───────────────────────────────────────────────────

[[ $# -lt 1 ]] && usage 1

TYPE="$1"
OUTPUT="${2:--}"

case "$TYPE" in
    go)     content=$(generate_go) ;;
    node)   content=$(generate_node) ;;
    python) content=$(generate_python) ;;
    docker) content=$(generate_docker) ;;
    c)      content=$(generate_c) ;;
    cpp|c++) content=$(generate_cpp) ;;
    -h|--help) usage 0 ;;
    *)
        echo "Error: Unknown project type '$TYPE'" >&2
        echo "Valid types: go, node, python, docker, c, cpp" >&2
        exit 1
        ;;
esac

if [[ "$OUTPUT" == "-" ]]; then
    echo "$content"
else
    # Create parent directories if needed
    mkdir -p "$(dirname "$OUTPUT")"
    if [[ -f "$OUTPUT" ]]; then
        echo "Warning: $OUTPUT already exists. Overwrite? [y/N]" >&2
        read -r ans
        [[ "$ans" != "y" && "$ans" != "Y" ]] && exit 1
    fi
    echo "$content" > "$OUTPUT"
    echo "Generated $TYPE Makefile → $OUTPUT" >&2
fi
