#!/usr/bin/env bash
# setup-haproxy.sh — Install and configure HAProxy with a production-ready configuration
#
# Features:
#   - Frontend with HTTP/HTTPS, redirect HTTP→HTTPS
#   - Backend pool with health checks and connection draining
#   - Stats dashboard on port 8404
#   - Rate limiting via stick tables
#   - Logging configuration
#
# Usage:
#   ./setup-haproxy.sh                          # Interactive setup
#   ./setup-haproxy.sh --backends "10.0.1.10:8080,10.0.1.11:8080"
#   ./setup-haproxy.sh --backends "10.0.1.10:8080" --ssl-cert /path/to/cert.pem
#   ./setup-haproxy.sh --dry-run                # Generate config only, don't install
#
# Options:
#   --backends      Comma-separated backend addresses (host:port)
#   --ssl-cert      Path to SSL certificate (PEM format, cert+key combined)
#   --stats-pass    Password for stats dashboard (default: auto-generated)
#   --algorithm     LB algorithm: roundrobin|leastconn|source (default: leastconn)
#   --health-path   Health check path (default: /healthz)
#   --dry-run       Generate config file without installing HAProxy
#   --config-only   Only generate config, skip installation (implies dry-run)
#   -h, --help      Show this help

set -euo pipefail

# --- Defaults ---
BACKENDS=""
SSL_CERT=""
STATS_PASS=""
ALGORITHM="leastconn"
HEALTH_PATH="/healthz"
DRY_RUN=false
CONFIG_ONLY=false
HAPROXY_CFG="/etc/haproxy/haproxy.cfg"
HAPROXY_CFG_BACKUP=""

# --- Colors ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
log_ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
log_fail()  { echo -e "${RED}[FAIL]${NC}  $*"; }

usage() {
    sed -n '2,18p' "$0" | sed 's/^# \?//'
    exit 0
}

# --- Parse arguments ---
while [[ $# -gt 0 ]]; do
    case "$1" in
        --backends)     BACKENDS="$2"; shift 2 ;;
        --ssl-cert)     SSL_CERT="$2"; shift 2 ;;
        --stats-pass)   STATS_PASS="$2"; shift 2 ;;
        --algorithm)    ALGORITHM="$2"; shift 2 ;;
        --health-path)  HEALTH_PATH="$2"; shift 2 ;;
        --dry-run)      DRY_RUN=true; shift ;;
        --config-only)  CONFIG_ONLY=true; DRY_RUN=true; shift ;;
        -h|--help)      usage ;;
        *) echo "Unknown option: $1"; usage ;;
    esac
done

# --- Interactive backend input if not provided ---
if [[ -z "$BACKENDS" ]]; then
    echo "Enter backend servers (comma-separated, e.g., 10.0.1.10:8080,10.0.1.11:8080):"
    read -r BACKENDS
    if [[ -z "$BACKENDS" ]]; then
        log_fail "No backends specified. Exiting."
        exit 1
    fi
fi

IFS=',' read -ra BACKEND_LIST <<< "$BACKENDS"

# Generate stats password if not provided
if [[ -z "$STATS_PASS" ]]; then
    STATS_PASS=$(openssl rand -base64 16 2>/dev/null || head -c 16 /dev/urandom | base64)
fi

echo "============================================"
echo "  HAProxy Setup"
echo "============================================"
echo "  Backends:      ${#BACKEND_LIST[@]} servers"
echo "  Algorithm:     $ALGORITHM"
echo "  Health check:  $HEALTH_PATH"
echo "  SSL:           ${SSL_CERT:-none}"
echo "  Dry run:       $DRY_RUN"
echo "============================================"
echo

# -----------------------------------------------
# Step 1: Install HAProxy (unless dry-run)
# -----------------------------------------------
if [[ "$DRY_RUN" == "false" ]]; then
    log_info "Installing HAProxy..."

    if command -v apt-get &>/dev/null; then
        sudo apt-get update -qq
        sudo apt-get install -y -qq haproxy
    elif command -v yum &>/dev/null; then
        sudo yum install -y -q haproxy
    elif command -v dnf &>/dev/null; then
        sudo dnf install -y -q haproxy
    elif command -v apk &>/dev/null; then
        sudo apk add --quiet haproxy
    else
        log_fail "Unsupported package manager. Install HAProxy manually."
        exit 1
    fi

    log_ok "HAProxy installed: $(haproxy -v 2>&1 | head -1)"
fi

# -----------------------------------------------
# Step 2: Generate Configuration
# -----------------------------------------------
log_info "Generating HAProxy configuration..."

# Build backend server lines
BACKEND_SERVERS=""
SERVER_NUM=1
for backend in "${BACKEND_LIST[@]}"; do
    backend=$(echo "$backend" | xargs)
    BACKEND_SERVERS+="    server app${SERVER_NUM} ${backend} check inter 5s fall 3 rise 2 weight 100 slowstart 60s
"
    SERVER_NUM=$((SERVER_NUM + 1))
done

# SSL bind line
SSL_BIND=""
SSL_REDIRECT=""
if [[ -n "$SSL_CERT" ]]; then
    SSL_BIND="    bind *:443 ssl crt ${SSL_CERT} alpn h2,http/1.1"
    SSL_REDIRECT='
    # Redirect HTTP to HTTPS
    http-request redirect scheme https unless { ssl_fc }'
fi

CONFIG=$(cat <<HAPROXY_CONFIG
# HAProxy Configuration
# Generated by setup-haproxy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Backends: ${#BACKEND_LIST[@]} servers, Algorithm: ${ALGORITHM}

#---------------------------------------------------------------------
# Global settings
#---------------------------------------------------------------------
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    # TLS tuning
    tune.ssl.default-dh-param 2048
    ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384
    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-bind-options ssl-min-ver TLSv1.2 no-tls-tickets

    # Performance tuning
    maxconn 50000
    tune.bufsize 32768

#---------------------------------------------------------------------
# Default settings
#---------------------------------------------------------------------
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    option  http-server-close
    option  forwardfor except 127.0.0.0/8

    timeout connect 5s
    timeout client  30s
    timeout server  60s
    timeout http-request 10s
    timeout http-keep-alive 5s
    timeout queue   30s
    timeout check   5s
    timeout tunnel  3600s

    # Error pages
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

    # Retry on connection failure
    retry-on conn-failure empty-response response-timeout

#---------------------------------------------------------------------
# Frontend: HTTP(S) entrypoint
#---------------------------------------------------------------------
frontend http_front
    bind *:80
${SSL_BIND}
${SSL_REDIRECT}
    # Request ID for tracing
    unique-id-format %{+X}o\ %ci:%cp_%fi:%fp_%Ts_%rt:%pid
    unique-id-header X-Request-ID

    # Security headers
    http-response set-header X-Frame-Options SAMEORIGIN
    http-response set-header X-Content-Type-Options nosniff
    http-response set-header X-XSS-Protection "1; mode=block"
    http-response set-header Strict-Transport-Security "max-age=31536000; includeSubDomains" if { ssl_fc }

    # Forwarded headers
    http-request set-header X-Forwarded-Proto https if { ssl_fc }
    http-request set-header X-Forwarded-Proto http  unless { ssl_fc }

    # Rate limiting via stick table
    stick-table type ip size 200k expire 5m store http_req_rate(10s),conn_cur
    http-request track-sc0 src

    # Deny if >100 requests in 10s from same IP
    acl rate_abuse sc_http_req_rate(0) gt 100
    http-request deny deny_status 429 if rate_abuse

    # Deny if >50 concurrent connections from same IP
    acl conn_abuse sc_conn_cur(0) gt 50
    http-request deny deny_status 429 if conn_abuse

    # ACL-based routing
    acl is_health path ${HEALTH_PATH}
    acl is_api path_beg /api
    acl is_ws hdr(Upgrade) -i websocket

    # Health check bypass (no rate limit)
    http-request allow if is_health

    # Route WebSocket to dedicated backend
    use_backend ws_backend if is_ws

    default_backend app_backend

#---------------------------------------------------------------------
# Backend: Application servers
#---------------------------------------------------------------------
backend app_backend
    balance ${ALGORITHM}

    # HTTP health checks
    option httpchk GET ${HEALTH_PATH}
    http-check expect status 200

    # Connection draining on marked-down servers
    default-server on-marked-down shutdown-sessions

    # Enable HTTP connection reuse
    http-reuse safe

    # Compression
    compression algo gzip
    compression type text/html text/plain text/css application/javascript application/json

    # Servers
${BACKEND_SERVERS}
#---------------------------------------------------------------------
# Backend: WebSocket servers (same pool, different settings)
#---------------------------------------------------------------------
backend ws_backend
    balance leastconn

    option httpchk GET ${HEALTH_PATH}
    http-check expect status 200

    timeout tunnel 3600s
    timeout server 3600s

    # Servers (same as app, adjust if WebSocket has dedicated pool)
${BACKEND_SERVERS}
#---------------------------------------------------------------------
# Stats dashboard
#---------------------------------------------------------------------
listen stats
    bind *:8404
    mode http
    stats enable
    stats uri /stats
    stats refresh 10s
    stats show-legends
    stats show-node
    stats auth admin:${STATS_PASS}

    # Restrict to internal networks (adjust as needed)
    # acl internal src 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16
    # http-request deny unless internal
HAPROXY_CONFIG
)

# -----------------------------------------------
# Step 3: Write Configuration
# -----------------------------------------------
if [[ "$DRY_RUN" == "true" ]]; then
    OUTPUT_FILE="./haproxy.cfg.generated"
    echo "$CONFIG" > "$OUTPUT_FILE"
    log_ok "Configuration written to: $OUTPUT_FILE"
    echo
    echo "--- Generated Configuration ---"
    echo "$CONFIG"
    echo "--- End Configuration ---"
else
    # Backup existing config
    if [[ -f "$HAPROXY_CFG" ]]; then
        HAPROXY_CFG_BACKUP="${HAPROXY_CFG}.backup.$(date +%Y%m%d%H%M%S)"
        sudo cp "$HAPROXY_CFG" "$HAPROXY_CFG_BACKUP"
        log_info "Backed up existing config to: $HAPROXY_CFG_BACKUP"
    fi

    echo "$CONFIG" | sudo tee "$HAPROXY_CFG" > /dev/null
    log_ok "Configuration written to: $HAPROXY_CFG"

    # Ensure socket directory exists
    sudo mkdir -p /run/haproxy

    # Validate configuration
    log_info "Validating configuration..."
    if sudo haproxy -c -f "$HAPROXY_CFG" 2>&1; then
        log_ok "Configuration is valid"
    else
        log_fail "Configuration validation failed!"
        if [[ -n "$HAPROXY_CFG_BACKUP" ]]; then
            sudo cp "$HAPROXY_CFG_BACKUP" "$HAPROXY_CFG"
            log_info "Restored backup configuration"
        fi
        exit 1
    fi

    # Restart HAProxy
    log_info "Restarting HAProxy..."
    if sudo systemctl restart haproxy 2>/dev/null; then
        log_ok "HAProxy restarted successfully"
    elif sudo service haproxy restart 2>/dev/null; then
        log_ok "HAProxy restarted successfully"
    else
        log_warn "Could not restart HAProxy automatically. Run: sudo systemctl restart haproxy"
    fi

    # Enable on boot
    sudo systemctl enable haproxy 2>/dev/null || true
fi

# -----------------------------------------------
# Summary
# -----------------------------------------------
echo
echo "============================================"
echo "  Setup Complete"
echo "============================================"
echo "  Frontend:    http://$(hostname -f 2>/dev/null || echo 'localhost'):80"
if [[ -n "$SSL_CERT" ]]; then
    echo "  Frontend:    https://$(hostname -f 2>/dev/null || echo 'localhost'):443"
fi
echo "  Stats:       http://$(hostname -f 2>/dev/null || echo 'localhost'):8404/stats"
echo "  Stats auth:  admin:${STATS_PASS}"
echo "  Config:      ${HAPROXY_CFG}"
echo
echo "  Backends:"
for backend in "${BACKEND_LIST[@]}"; do
    echo "    - $(echo "$backend" | xargs)"
done
echo
echo "  Useful commands:"
echo "    haproxy -c -f ${HAPROXY_CFG}              # Validate config"
echo "    systemctl status haproxy                    # Check status"
echo "    echo 'show stat' | socat stdio /run/haproxy/admin.sock  # Runtime stats"
echo "    echo 'show servers state' | socat stdio /run/haproxy/admin.sock"
echo "============================================"
