#!/usr/bin/env bash
# nginx-ssl-setup.sh — Automates SSL certificate setup with Let's Encrypt
#
# Usage:
#   ./nginx-ssl-setup.sh <domain> [--email admin@example.com] [--webroot /var/www/html]
#   ./nginx-ssl-setup.sh example.com --email admin@example.com
#   ./nginx-ssl-setup.sh example.com --webroot /var/www/html --staging
#
# Features:
#   - Installs certbot if not present
#   - Obtains SSL certificate via Let's Encrypt
#   - Generates strong DH parameters (if not already present)
#   - Configures OCSP stapling
#   - Creates ssl-params.conf snippet
#   - Sets up auto-renewal via systemd timer
#
# Requirements: root/sudo, nginx installed, domain pointing to this server

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

usage() {
    echo "Usage: $0 <domain> [options]"
    echo ""
    echo "Options:"
    echo "  --email EMAIL      Email for Let's Encrypt notifications (required)"
    echo "  --webroot PATH     Webroot path (default: /var/www/html)"
    echo "  --staging          Use Let's Encrypt staging server (for testing)"
    echo "  --skip-dhparam     Skip DH parameter generation"
    echo "  --nginx-conf-dir   Nginx config directory (default: /etc/nginx)"
    echo "  -h, --help         Show this help"
    exit 1
}

# --- Parse arguments ---
DOMAIN=""
EMAIL=""
WEBROOT="/var/www/html"
STAGING=""
SKIP_DHPARAM=false
NGINX_CONF_DIR="/etc/nginx"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --email)       EMAIL="$2"; shift 2 ;;
        --webroot)     WEBROOT="$2"; shift 2 ;;
        --staging)     STAGING="--staging"; shift ;;
        --skip-dhparam) SKIP_DHPARAM=true; shift ;;
        --nginx-conf-dir) NGINX_CONF_DIR="$2"; shift 2 ;;
        -h|--help)     usage ;;
        -*)            log_error "Unknown option: $1"; usage ;;
        *)             DOMAIN="$1"; shift ;;
    esac
done

if [[ -z "$DOMAIN" ]]; then
    log_error "Domain is required"
    usage
fi

if [[ -z "$EMAIL" ]]; then
    log_error "--email is required for Let's Encrypt notifications"
    usage
fi

# --- Check prerequisites ---
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root (or with sudo)"
    exit 1
fi

if ! command -v nginx &>/dev/null; then
    log_error "nginx is not installed"
    exit 1
fi

# --- Install certbot if needed ---
if ! command -v certbot &>/dev/null; then
    log_info "Installing certbot..."
    if command -v apt-get &>/dev/null; then
        apt-get update -qq
        apt-get install -y -qq certbot python3-certbot-nginx
    elif command -v dnf &>/dev/null; then
        dnf install -y -q certbot python3-certbot-nginx
    elif command -v yum &>/dev/null; then
        yum install -y -q certbot python3-certbot-nginx
    else
        log_error "Cannot determine package manager. Install certbot manually."
        exit 1
    fi
    log_info "certbot installed successfully"
fi

# --- Create snippets directory ---
SNIPPETS_DIR="${NGINX_CONF_DIR}/snippets"
mkdir -p "$SNIPPETS_DIR"

# --- Generate DH parameters ---
DHPARAM_FILE="${NGINX_CONF_DIR}/dhparam.pem"
if [[ "$SKIP_DHPARAM" == false ]] && [[ ! -f "$DHPARAM_FILE" ]]; then
    log_info "Generating DH parameters (4096-bit). This will take several minutes..."
    openssl dhparam -out "$DHPARAM_FILE" 4096
    chmod 644 "$DHPARAM_FILE"
    log_info "DH parameters generated: $DHPARAM_FILE"
elif [[ -f "$DHPARAM_FILE" ]]; then
    log_info "DH parameters already exist: $DHPARAM_FILE"
fi

# --- Obtain SSL certificate ---
log_info "Obtaining SSL certificate for ${DOMAIN}..."
certbot certonly \
    --nginx \
    --non-interactive \
    --agree-tos \
    --email "$EMAIL" \
    --domain "$DOMAIN" \
    --domain "www.${DOMAIN}" \
    ${STAGING} \
    || {
        log_warn "Nginx plugin failed. Trying webroot method..."
        mkdir -p "$WEBROOT"
        certbot certonly \
            --webroot \
            --webroot-path "$WEBROOT" \
            --non-interactive \
            --agree-tos \
            --email "$EMAIL" \
            --domain "$DOMAIN" \
            --domain "www.${DOMAIN}" \
            ${STAGING}
    }

log_info "SSL certificate obtained successfully"

# --- Create SSL params snippet ---
SSL_PARAMS_FILE="${SNIPPETS_DIR}/ssl-params.conf"
cat > "$SSL_PARAMS_FILE" << 'SSLEOF'
# SSL/TLS parameters — modern configuration
# Generated by nginx-ssl-setup.sh

ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305';
ssl_prefer_server_ciphers off;
ssl_ecdh_curves X25519:secp384r1:secp256r1;

ssl_session_cache shared:SSL:10m;
ssl_session_timeout 1d;
ssl_session_tickets off;

ssl_stapling on;
ssl_stapling_verify on;
resolver 1.1.1.1 8.8.8.8 valid=300s;
resolver_timeout 5s;

add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
SSLEOF

# Add DH params if generated
if [[ -f "$DHPARAM_FILE" ]]; then
    echo "ssl_dhparam ${DHPARAM_FILE};" >> "$SSL_PARAMS_FILE"
fi

log_info "SSL params snippet created: $SSL_PARAMS_FILE"

# --- Create server block template ---
SITE_CONF="${NGINX_CONF_DIR}/sites-available/${DOMAIN}.conf"
if [[ ! -f "$SITE_CONF" ]]; then
    CERT_DIR="/etc/letsencrypt/live/${DOMAIN}"
    cat > "$SITE_CONF" << EOF
# HTTP → HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN} www.${DOMAIN};
    return 301 https://\$host\$request_uri;
}

# HTTPS server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAIN} www.${DOMAIN};

    ssl_certificate ${CERT_DIR}/fullchain.pem;
    ssl_certificate_key ${CERT_DIR}/privkey.pem;
    ssl_trusted_certificate ${CERT_DIR}/chain.pem;
    include ${SNIPPETS_DIR}/ssl-params.conf;

    root ${WEBROOT};
    index index.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF
    log_info "Server block template created: $SITE_CONF"

    # Enable the site
    if [[ -d "${NGINX_CONF_DIR}/sites-enabled" ]]; then
        ln -sf "$SITE_CONF" "${NGINX_CONF_DIR}/sites-enabled/${DOMAIN}.conf"
        log_info "Site enabled via symlink"
    fi
fi

# --- Test and reload nginx ---
log_info "Testing nginx configuration..."
if nginx -t 2>&1; then
    nginx -s reload
    log_info "Nginx reloaded successfully"
else
    log_error "Nginx config test failed. Please fix errors before reloading."
    exit 1
fi

# --- Set up auto-renewal ---
if systemctl list-unit-files | grep -q certbot.timer; then
    systemctl enable certbot.timer
    systemctl start certbot.timer
    log_info "Certbot auto-renewal timer enabled"
else
    # Fallback: add cron job
    CRON_CMD="0 3 * * * certbot renew --quiet --deploy-hook 'nginx -s reload'"
    if ! crontab -l 2>/dev/null | grep -q "certbot renew"; then
        (crontab -l 2>/dev/null; echo "$CRON_CMD") | crontab -
        log_info "Certbot renewal cron job added"
    fi
fi

# --- Summary ---
echo ""
log_info "========================================="
log_info "SSL setup complete for ${DOMAIN}"
log_info "========================================="
echo ""
echo "  Certificate:    /etc/letsencrypt/live/${DOMAIN}/fullchain.pem"
echo "  Private Key:    /etc/letsencrypt/live/${DOMAIN}/privkey.pem"
echo "  SSL Params:     ${SSL_PARAMS_FILE}"
echo "  DH Params:      ${DHPARAM_FILE}"
echo "  Server Config:  ${SITE_CONF}"
echo ""
echo "  Verify SSL: openssl s_client -connect ${DOMAIN}:443 -servername ${DOMAIN}"
echo "  Test grade: https://www.ssllabs.com/ssltest/analyze.html?d=${DOMAIN}"
echo ""
